"""Training loop for the AlphaZero-style chess learner (v2, Sprint A/C).

run() orchestrates: self-play (teacher = accepted best) -> real bounded shuffled
epochs -> arena gate -> durable checkpoint. CPU-friendly: everything runs on
cfg.device (auto CPU if no CUDA).

Checkpointing (schema_version=2):
  - `latest.pt` : full resumable training state written ATOMICALLY after every
                  completed iteration and again in `finally` on graceful
                  interruption (reason="interrupt") or normal completion
                  (reason="final").  Payload: schema_version, run_id,
                  iteration, generation, optimizer_steps, candidate, best,
                  optimizer, torch/cuda/random/numpy RNGs, compressed replay
                  (state_dict), and a JSON-safe config snapshot.
  - `checkpoint_meta.json` : sidecar written atomically next to latest.pt with
                  the same run_id/iteration/generation/optimizer_steps plus
                  reason and saved_at.
  - `ckpt-iterNNNN-<timestamp>.pt` : hardlink snapshot of each per-iteration
                  latest.pt (never overwritten), so checkpoint history is
                  countable.
  - `best.pt`    : serving artifact holding the accepted best net's state dict.

Resume:  `resume=True` restores candidate, accepted best, optimizer, RNGs,
compressed replay, run_id, generation, iteration and the config snapshot.
Legacy v1 snapshots (no schema_version, or schema_version != 2) raise
IncompatibleCheckpointError with a clear message and are NEVER auto-loaded; a
fresh (non-resume) start archives any stale latest.pt instead of reading it.

Learning semantics (Sprint C):
  - training does `training_epochs` real epochs over a bounded sample drawn
    from the replay buffer, freshly shuffled per epoch; each minibatch is one
    optimizer step.  Policy loss (cross-entropy), value loss (MSE) and policy
    entropy are tracked separately; optimizer_steps counts actual step() calls.
  - self-play is generated by the ACCEPTED best net; a rejected challenger is
    reverted to best and its optimizer is reset, so it can never silently
    become the next teacher.
  - the arena uses the standard score (wins + 0.5*draws) / games; acceptance
    installs the candidate as best and increments generation.
  - metrics are event-only: iteration records carry run_id/generation/
    policy/value/entropy/optimizer_steps/replay_size/games; arena outcomes are
    separate `event: "arena"` records.

Parallel mode (run_parallel) consumes worker result ENVELOPES ({"kind":
"game"|"error", ...}) with a timeout and worker-liveness checks so a dead
worker or a stuck queue becomes a bounded RuntimeError, never an unbounded
Queue.get() hang.  Legacy raw-example lists are still accepted.
"""

import json
import os
import queue
import random
import shutil
import time
import uuid
from datetime import datetime, timezone

import numpy as np
import torch
import torch.nn.functional as F

from config import Config
from model import ChessNet
from selfplay import play_game
from arena import play_match
from parallel import InferenceServer, worker_loop
from replay import ReplayBuffer

Adam = torch.optim.Adam  # module alias so tests can substitute a spy

CHECKPOINT_SCHEMA_VERSION = 2
METRICS_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "training.jsonl")


class IncompatibleCheckpointError(RuntimeError):
    """Raised when a resume target is not a schema_version=2 checkpoint."""


# --------------------------------------------------------------------------- #
#  logging / metrics                                                           #
# --------------------------------------------------------------------------- #

def _metrics_path(cfg):
    return getattr(cfg, "metrics_path", None) or METRICS_PATH


def _log_metrics(cfg, *, run_id, iteration, generation, policy_loss,
                 value_loss, entropy, optimizer_steps, replay_size, games):
    """Append one iteration record to the metrics file (machine-readable)."""
    try:
        rec = {
            "t": time.time(),
            "run_id": run_id,
            "iteration": int(iteration),
            "generation": int(generation),
            "policy_loss": round(float(policy_loss), 6),
            "value_loss": round(float(value_loss), 6),
            "entropy": round(float(entropy), 6),
            "optimizer_steps": int(optimizer_steps),
            "replay_size": int(replay_size),
            "games": int(games),
        }
        with open(_metrics_path(cfg), "a") as f:
            f.write(json.dumps(rec) + "\n")
    except Exception:  # noqa: BLE001 - observability must never kill training
        pass


def _log_arena_event(cfg, *, run_id, iteration, generation, wins, draws,
                     losses, score, accepted):
    """Append one event-only arena record (never folded into iteration metrics)."""
    try:
        rec = {
            "t": time.time(),
            "run_id": run_id,
            "event": "arena",
            "iteration": int(iteration),
            "generation": int(generation),
            "wins": int(wins),
            "draws": int(draws),
            "losses": int(losses),
            "score": round(float(score), 6),
            "accepted": bool(accepted),
        }
        with open(_metrics_path(cfg), "a") as f:
            f.write(json.dumps(rec) + "\n")
    except Exception:  # noqa: BLE001
        pass


# --------------------------------------------------------------------------- #
#  config snapshot / run identity                                              #
# --------------------------------------------------------------------------- #

def _config_snapshot(cfg):
    """JSON-safe subset of the config (class attrs + instance overrides)."""
    snap = {}
    for k in dir(cfg):
        if k.startswith("_"):
            continue
        try:
            v = getattr(cfg, k)
        except Exception:  # noqa: BLE001
            continue
        if isinstance(v, (str, int, float, bool)) or v is None:
            snap[k] = v
    return snap


def _make_run_id(cfg):
    rid = getattr(cfg, "run_id", None)
    if rid:
        return str(rid)
    return uuid.uuid4().hex[:12]


def _seed_all(seed):
    torch.manual_seed(seed)
    random.seed(seed)
    np.random.seed(seed)


# --------------------------------------------------------------------------- #
#  checkpointing (schema_version=2)                                            #
# --------------------------------------------------------------------------- #

def _checkpoint_paths(cfg):
    return {
        "best": os.path.join(cfg.checkpoint_dir, "best.pt"),
        "latest": os.path.join(cfg.checkpoint_dir, "latest.pt"),
        "meta": os.path.join(cfg.checkpoint_dir, "checkpoint_meta.json"),
    }


def _timestamp():
    return time.strftime("%Y%m%d-%H%M%S")


def _save_best_atomic(cfg, net):
    """Atomically publish arena-accepted weights for serving/evaluation."""
    path = _checkpoint_paths(cfg)["best"]
    tmp = path + ".tmp"
    torch.save(net.state_dict(), tmp)
    os.replace(tmp, path)
    return path


def _save_meta(cfg, *, run_id, iteration, generation, optimizer_steps,
               replay_size, reason):
    """Atomically write checkpoint_meta.json next to latest.pt."""
    paths = _checkpoint_paths(cfg)
    meta = {
        "schema_version": CHECKPOINT_SCHEMA_VERSION,
        "run_id": run_id,
        "iteration": int(iteration),
        "generation": int(generation),
        "optimizer_steps": int(optimizer_steps),
        "replay_size": int(replay_size),
        "reason": reason,
        "saved_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "config": _config_snapshot(cfg),
    }
    tmp = paths["meta"] + ".tmp"
    with open(tmp, "w") as f:
        json.dump(meta, f, indent=2, sort_keys=True)
    os.replace(tmp, paths["meta"])
    return paths["meta"]


def _mark_checkpoint_reason(cfg, reason):
    """Update only the sidecar reason for an already-durable checkpoint."""
    path = _checkpoint_paths(cfg)["meta"]
    if not os.path.exists(path):
        return None
    with open(path) as f:
        meta = json.load(f)
    meta["reason"] = reason
    meta["saved_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(meta, f, indent=2, sort_keys=True)
    os.replace(tmp, path)
    return path


def _save_latest(cfg, *, run_id, iteration, generation, optimizer_steps,
                 net, best_net, optimizer, buffer, reason):
    """Persist a full resumable v2 snapshot to `latest.pt` (atomic) plus
    checkpoint_meta.json (atomic)."""
    paths = _checkpoint_paths(cfg)
    payload = {
        "schema_version": CHECKPOINT_SCHEMA_VERSION,
        "run_id": run_id,
        "iteration": int(iteration),
        "generation": int(generation),
        "optimizer_steps": int(optimizer_steps),
        "candidate": net.state_dict(),
        "best": best_net.state_dict(),
        "optimizer": optimizer.state_dict(),
        "torch_rng": torch.get_rng_state(),
        "cuda_rng": torch.cuda.get_rng_state_all() if torch.cuda.is_available() else None,
        "random_rng": random.getstate(),
        "numpy_rng": np.random.get_state(),
        "replay": buffer.state_dict(),
        "config": _config_snapshot(cfg),
    }
    tmp = paths["latest"] + ".tmp"
    torch.save(payload, tmp)
    os.replace(tmp, paths["latest"])
    _save_meta(cfg, run_id=run_id, iteration=iteration, generation=generation,
               optimizer_steps=optimizer_steps, replay_size=len(buffer),
               reason=reason)
    return paths["latest"]


def _load_latest_v2(cfg):
    """Return the latest resumable v2 snapshot, or None if it doesn't exist.

    Raises IncompatibleCheckpointError for legacy/unknown schema — v1
    checkpoints are never auto-loaded.
    """
    path = _checkpoint_paths(cfg)["latest"]
    if not os.path.exists(path):
        return None
    # weights_only=False: the snapshot is self-created and trusted, and it
    # carries non-tensor state (numpy/RNG) that weights_only=True rejects.
    payload = torch.load(path, map_location=getattr(cfg, "device", "cpu"),
                         weights_only=False)
    version = payload.get("schema_version")
    if version != CHECKPOINT_SCHEMA_VERSION:
        raise IncompatibleCheckpointError(
            f"checkpoint {path} has schema_version={version!r}; expected "
            f"{CHECKPOINT_SCHEMA_VERSION}. This looks like a v1 checkpoint — "
            "v1 snapshots are not auto-loadable. Start fresh (or convert) and "
            "resume only from a v2 latest.pt."
        )
    return payload


def _restore_rng(state):
    """Restore torch/cuda/random/numpy RNG states from a v2 snapshot."""
    rng = state["torch_rng"]
    torch.set_rng_state(rng.cpu() if rng.is_cuda else rng)
    if state.get("cuda_rng") and torch.cuda.is_available():
        cuda_rng = state["cuda_rng"]
        if isinstance(cuda_rng, (list, tuple)) and all(
            hasattr(r, "cpu") for r in cuda_rng
        ):
            torch.cuda.set_rng_state_all(
                [r.cpu() if r.is_cuda else r for r in cuda_rng]
            )
    random.setstate(state["random_rng"])
    np.random.set_state(state["numpy_rng"])


def _archive_best(cfg):
    """Move an existing best.pt out of the way before it's overwritten, so a
    fresh (non-resume) start can never silently destroy the incumbent best net."""
    best_path = _checkpoint_paths(cfg)["best"]
    if os.path.exists(best_path):
        archived = os.path.join(cfg.checkpoint_dir, f"best-{_timestamp()}.pt")
        os.replace(best_path, archived)
        print(f"Archived previous best -> {os.path.basename(archived)}", flush=True)


def _archive_latest(cfg):
    """Move an existing latest.pt out of the way on a fresh (non-resume) start
    so a legacy/foreign snapshot is preserved and never silently loaded."""
    latest_path = _checkpoint_paths(cfg)["latest"]
    if os.path.exists(latest_path):
        archived = os.path.join(cfg.checkpoint_dir, f"latest-{_timestamp()}.pt")
        os.replace(latest_path, archived)
        print(f"Archived previous latest -> {os.path.basename(archived)}", flush=True)


def _snapshot_checkpoint(cfg, iteration):
    """Hardlink the just-written latest.pt to a versioned, never-overwritten
    filename so checkpoints are countable and recoverable after a reset."""
    latest_path = _checkpoint_paths(cfg)["latest"]
    if not os.path.exists(latest_path):
        return None
    versioned = os.path.join(
        cfg.checkpoint_dir, f"ckpt-iter{iteration:04d}-{_timestamp()}.pt"
    )
    try:
        os.link(latest_path, versioned)
    except OSError:
        shutil.copy2(latest_path, versioned)
    return versioned


# --------------------------------------------------------------------------- #
#  training / arena semantics                                                  #
# --------------------------------------------------------------------------- #

def _new_optimizer(cfg, net):
    return Adam(net.parameters(), lr=cfg.learning_rate,
                weight_decay=getattr(cfg, "weight_decay", 1e-4))


def _epoch_train(cfg, net, optimizer, buffer, device):
    """Run `training_epochs` REAL epochs over a bounded, per-epoch-shuffled
    sample from the replay buffer.  Each minibatch is one optimizer step.

    Returns dict(policy_loss, value_loss, entropy, steps, batches) — losses are
    averaged over all minibatches, steps counts actual optimizer.step() calls.
    """
    n = len(buffer)
    epochs = int(getattr(cfg, "training_epochs",
                         getattr(cfg, "epochs_per_iteration", 3)))
    if n == 0 or epochs <= 0:
        return {"policy_loss": 0.0, "value_loss": 0.0, "entropy": 0.0,
                "steps": 0, "batches": 0}
    sample_size = min(
        n,
        int(getattr(cfg, "train_epoch_size", 0)
            or (cfg.train_batch_size * epochs)),
    )
    if sample_size <= 0:
        return {"policy_loss": 0.0, "value_loss": 0.0, "entropy": 0.0,
                "steps": 0, "batches": 0}

    net.train()
    sum_policy = sum_value = sum_entropy = 0.0
    steps = batches = 0
    for _ in range(epochs):
        # Uniform sample from the entire replay, freshly shuffled each epoch.
        # Sampling only permutation(sample_size) would repeatedly train the
        # oldest prefix and starve newly generated positions.
        rows = np.random.choice(n, size=sample_size, replace=False)
        for start in range(0, sample_size, cfg.train_batch_size):
            batch_rows = rows[start:start + cfg.train_batch_size]
            states, pis, zs = buffer.sample_indices(batch_rows, device)
            logits, value = net(states)
            policy_loss = F.cross_entropy(logits, pis)
            value_loss = F.mse_loss(value, zs)
            probs = F.softmax(logits, dim=1)
            entropy = -(probs * (probs + 1e-12).log()).sum(dim=1).mean()
            loss = policy_loss + value_loss
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            sum_policy += float(policy_loss.item())
            sum_value += float(value_loss.item())
            sum_entropy += float(entropy.item())
            steps += 1
            batches += 1
    return {
        "policy_loss": sum_policy / batches,
        "value_loss": sum_value / batches,
        "entropy": sum_entropy / batches,
        "steps": steps,
        "batches": batches,
    }


def _arena_gate(cfg, net, best_net):
    """Candidate vs incumbent best.  Standard score = (wins + 0.5*draws)/games.

    Returns dict(a, b, draws, games, score, accepted).
    """
    net.eval()
    best_net.eval()
    result = play_match(net, best_net, cfg, num_games=cfg.arena_games)
    wins = int(result["a"])
    losses = int(result["b"])
    draws = int(result["draws"])
    games = wins + losses + draws
    score = (wins + 0.5 * draws) / games if games else 0.0
    accepted = score >= float(getattr(cfg, "arena_accept_threshold", 0.55))
    return {"a": wins, "b": losses, "draws": draws, "games": games,
            "score": score, "accepted": accepted}


# --------------------------------------------------------------------------- #
#  parallel result envelopes (timeout + liveness)                              #
# --------------------------------------------------------------------------- #

def _unpack_worker_result(item):
    """Normalize a parallel self-play result into ("game", examples) or
    ("error", detail).  Accepts the envelope format
    {"kind": "game"|"error", ...} (examples under "examples"/"payload") and
    the legacy raw-example list, so train.py is forward-compatible with
    parallel.py's result envelopes.
    """
    if isinstance(item, dict):
        kind = item.get("kind")
        if kind == "error":
            detail = (item.get("traceback") or item.get("message")
                      or item.get("error") or "unknown worker error")
            return "error", str(detail)
        if kind == "game":
            payload = item.get("examples", item.get("game",
                                                    item.get("payload", None)))
            if payload is None:
                return "unknown", item
            return "game", list(payload)
        return "unknown", item
    if isinstance(item, (list, tuple)):
        return "game", list(item)
    return "unknown", item


def _collect_games(cfg, result_queue, procs, games_needed, stop_event=None,
                   expected_generation=None, server=None):
    """Collect exactly ``games_needed`` game envelopes and flatten examples.

    Queue silence, worker/server death, protocol mismatch, or an error envelope
    becomes a bounded RuntimeError. When ``expected_generation`` is supplied,
    stale games from a previous accepted teacher are discarded.
    """
    timeout = float(getattr(cfg, "result_timeout_seconds", 60))
    examples = []
    game_count = 0
    while game_count < games_needed:
        if stop_event is not None and stop_event.is_set():
            raise RuntimeError("self-play stopped before enough games were collected")
        if server is not None and not server.is_alive():
            detail = server.get_error() if hasattr(server, "get_error") else None
            raise RuntimeError(f"inference server stopped: {detail or 'unknown error'}")
        try:
            item = result_queue.get(timeout=timeout)
        except queue.Empty:
            dead = [p for p in procs if not p.is_alive()]
            if dead:
                raise RuntimeError(
                    f"{len(dead)} self-play worker(s) died while waiting for games"
                )
            if server is not None and not server.is_alive():
                detail = server.get_error() if hasattr(server, "get_error") else None
                raise RuntimeError(f"inference server stopped: {detail or 'unknown error'}")
            raise RuntimeError(
                f"timed out after {timeout}s without a completed self-play game"
            )

        kind, payload = _unpack_worker_result(item)
        if kind == "error":
            raise RuntimeError(f"self-play worker error: {payload}")
        if kind != "game":
            raise RuntimeError(f"unknown self-play result envelope: {item!r}")
        if expected_generation is not None and isinstance(item, dict):
            item_generation = item.get("generation")
            if item_generation is not None and int(item_generation) != int(expected_generation):
                continue
        examples.extend(payload)
        game_count += 1
    return examples


# --------------------------------------------------------------------------- #
#  serial loop                                                                 #
# --------------------------------------------------------------------------- #

def run(cfg=None, resume=False, on_iteration=None):
    """The full self-play / train / arena loop.

    `on_iteration(iteration)` is called after each completed iteration (and its
    checkpoint); raising from it simulates a graceful interruption, which is
    still checkpointed in `finally`.
    """
    if cfg is None:
        cfg = Config()

    _seed_all(cfg.seed)
    os.makedirs(cfg.checkpoint_dir, exist_ok=True)
    device = getattr(cfg, "device", "cpu")

    net = ChessNet(cfg).to(device)
    best_net = ChessNet(cfg).to(device)
    best_net.load_state_dict(net.state_dict())
    optimizer = _new_optimizer(cfg, net)
    buffer = ReplayBuffer(
        cfg.replay_buffer_size, cfg.policy_size,
        getattr(cfg, "num_input_planes", 104),
        getattr(cfg, "board_size", 8),
    )

    start_iteration = 1
    generation = 0
    optimizer_steps = 0
    run_id = _make_run_id(cfg)

    if resume:
        state = _load_latest_v2(cfg)  # raises IncompatibleCheckpointError for v1
        if state is not None:
            net.load_state_dict(state["candidate"])
            best_net.load_state_dict(state["best"])
            optimizer.load_state_dict(state["optimizer"])
            _restore_rng(state)
            buffer.load_state_dict(state["replay"])
            run_id = state["run_id"]
            generation = int(state["generation"])
            optimizer_steps = int(state["optimizer_steps"])
            start_iteration = int(state["iteration"]) + 1
            print(
                f"Resumed run {run_id} (next iter {start_iteration}, "
                f"generation {generation}, steps {optimizer_steps})",
                flush=True,
            )

    best_path = _checkpoint_paths(cfg)["best"]
    if not resume:
        _archive_best(cfg)
        _archive_latest(cfg)   # never auto-load a stale/legacy latest.pt
    _save_best_atomic(cfg, best_net)

    games_played = (start_iteration - 1) * cfg.games_per_iteration
    num_iterations = int(getattr(cfg, "num_iterations", 1))
    iteration = start_iteration - 1
    completed_iteration = start_iteration - 1
    interrupted = False

    try:
        for iteration in range(start_iteration, num_iterations + 1):
            # ---- 1. self-play with the ACCEPTED best as teacher ----
            net.eval()
            best_net.eval()
            for _ in range(cfg.games_per_iteration):
                buffer.extend(play_game(best_net, cfg))
                games_played += 1

            # ---- 2. real bounded shuffled epochs ----
            train_out = _epoch_train(cfg, net, optimizer, buffer, device)
            optimizer_steps += train_out["steps"]

            # ---- 3. arena gate: candidate vs incumbent best ----
            if iteration % int(getattr(cfg, "arena_every", 10)) == 0:
                outcome = _arena_gate(cfg, net, best_net)
                if outcome["accepted"]:
                    generation += 1
                    best_net.load_state_dict(net.state_dict())
                    best_net.eval()
                    _save_best_atomic(cfg, best_net)
                else:
                    # Rejected challenger: revert to best and reset the
                    # optimizer so it can never silently become the teacher.
                    net.load_state_dict(best_net.state_dict())
                    optimizer = _new_optimizer(cfg, net)
                    optimizer_steps = 0
                _log_arena_event(
                    cfg, run_id=run_id, iteration=iteration,
                    generation=generation, wins=outcome["a"],
                    draws=outcome["draws"], losses=outcome["b"],
                    score=outcome["score"], accepted=outcome["accepted"],
                )

            # ---- 4. durable checkpoint after EVERY completed iteration ----
            _save_latest(cfg, run_id=run_id, iteration=iteration,
                         generation=generation,
                         optimizer_steps=optimizer_steps, net=net,
                         best_net=best_net, optimizer=optimizer,
                         buffer=buffer, reason="iteration")
            completed_iteration = iteration
            if iteration % int(getattr(cfg, "checkpoint_every_iterations", 1)) == 0:
                _snapshot_checkpoint(cfg, iteration)

            _log_metrics(cfg, run_id=run_id, iteration=iteration,
                         generation=generation,
                         policy_loss=train_out["policy_loss"],
                         value_loss=train_out["value_loss"],
                         entropy=train_out["entropy"],
                         optimizer_steps=optimizer_steps,
                         replay_size=len(buffer), games=games_played)
            print(
                f"iter {iteration:4d}  gen {generation}  steps {optimizer_steps}"
                f"  buffer {len(buffer)}  "
                f"p {train_out['policy_loss']:.4f} v {train_out['value_loss']:.4f}",
                flush=True,
            )
            if on_iteration is not None:
                on_iteration(iteration)
    except BaseException:
        interrupted = True
        raise
    finally:
        # A partial iteration is never checkpointed. Each completed iteration
        # was already saved atomically above; an interrupt only annotates that
        # last good checkpoint. Normal completion writes a final reason marker.
        if interrupted:
            if completed_iteration >= start_iteration:
                _mark_checkpoint_reason(cfg, "interrupt")
            reason = "interrupt"
        elif completed_iteration >= start_iteration:
            _save_latest(cfg, run_id=run_id, iteration=completed_iteration,
                         generation=generation,
                         optimizer_steps=optimizer_steps, net=net,
                         best_net=best_net, optimizer=optimizer,
                         buffer=buffer, reason="final")
            reason = "final"
        else:
            reason = "interrupt" if interrupted else "final"
        print(
            f"{'Training interrupted' if interrupted else 'Training complete.'} "
            f"(saved iteration {completed_iteration}, reason={reason})",
            flush=True,
        )
    _save_best_atomic(cfg, best_net)
    if not interrupted:
        print("Training complete.", flush=True)


# --------------------------------------------------------------------------- #
#  parallel loop                                                               #
# --------------------------------------------------------------------------- #

def run_parallel(cfg=None, resume=False, num_workers=None, on_iteration=None):
    """Self-play / train / arena loop with parallel self-play worker processes.

    CPU-heavy MCTS work runs in `num_workers` processes (one game each, in
    parallel); a shared GPU inference server (a thread here) coalesces their
    leaf evaluations into fat forward passes.  The trainer process owns the
    training net, the arena incumbent (self-play teacher), and the served
    `search_net` copy.  Worker results are consumed as envelopes with
    timeout + liveness checks (see _collect_games).
    """
    import multiprocessing as mp

    if cfg is None:
        cfg = Config()
    if num_workers is None or num_workers < 1:
        num_workers = max(1, getattr(cfg, "selfplay_workers", 8))

    _seed_all(cfg.seed)
    os.makedirs(cfg.checkpoint_dir, exist_ok=True)
    device = getattr(cfg, "device", "cpu")

    # ---- model / optimizer / resume (same semantics as serial run) ----
    net = ChessNet(cfg).to(device)
    best_net = ChessNet(cfg).to(device)
    best_net.load_state_dict(net.state_dict())
    search_net = ChessNet(cfg).to(device)
    search_net.load_state_dict(net.state_dict())
    search_net.eval()
    optimizer = _new_optimizer(cfg, net)
    buffer = ReplayBuffer(
        cfg.replay_buffer_size, cfg.policy_size,
        getattr(cfg, "num_input_planes", 104),
        getattr(cfg, "board_size", 8),
    )

    start_iteration = 1
    generation = 0
    optimizer_steps = 0
    run_id = _make_run_id(cfg)

    if resume:
        state = _load_latest_v2(cfg)  # raises IncompatibleCheckpointError for v1
        if state is not None:
            net.load_state_dict(state["candidate"])
            best_net.load_state_dict(state["best"])
            optimizer.load_state_dict(state["optimizer"])
            _restore_rng(state)
            buffer.load_state_dict(state["replay"])
            run_id = state["run_id"]
            generation = int(state["generation"])
            optimizer_steps = int(state["optimizer_steps"])
            start_iteration = int(state["iteration"]) + 1
            # Self-play always starts from the accepted teacher, never the
            # in-progress candidate restored from the checkpoint.
            search_net.load_state_dict(best_net.state_dict())
            print(
                f"Resumed run {run_id} (next iter {start_iteration}, "
                f"generation {generation}, steps {optimizer_steps})",
                flush=True,
            )

    best_path = _checkpoint_paths(cfg)["best"]
    if not resume:
        _archive_best(cfg)
        _archive_latest(cfg)
    _save_best_atomic(cfg, best_net)

    # ---- spawn worker processes + inference server ----
    ctx = mp.get_context("spawn")
    channels = []
    procs = []
    result_queue = ctx.Queue(maxsize=max(8, num_workers * 2))
    stop_event = ctx.Event()
    teacher_generation = ctx.Value("i", generation)
    for i in range(num_workers):
        req_q = ctx.Queue(maxsize=8)
        resp_q = ctx.Queue(maxsize=8)
        channels.append((req_q, resp_q))
        p = ctx.Process(
            target=worker_loop,
            args=(cfg, req_q, resp_q, result_queue, cfg.seed + 1000 + i,
                  stop_event, i, teacher_generation),
            daemon=True,
        )
        procs.append(p)

    server = InferenceServer(
        search_net, device, channels,
        max_batch=getattr(cfg, "inference_max_batch", 4096),
        min_batch=getattr(cfg, "inference_min_batch", 256),
    )
    server.start()
    for p in procs:
        p.start()
    print(
        f"[parallel] {num_workers} self-play workers + inference server",
        flush=True,
    )

    games_played = (start_iteration - 1) * cfg.games_per_iteration
    num_iterations = int(getattr(cfg, "num_iterations", 1))
    iteration = start_iteration - 1
    completed_iteration = start_iteration - 1
    interrupted = False

    try:
        for iteration in range(start_iteration, num_iterations + 1):
            # ---- 1. self-play: collect games from workers (teacher = best) ----
            server.update_weights(best_net.state_dict())
            # Publish the generation only after the corresponding weights are
            # live. Games already in progress retain their old tag and are
            # discarded by _collect_games after an arena promotion.
            teacher_generation.value = generation
            games = _collect_games(
                cfg, result_queue, procs, cfg.games_per_iteration, stop_event,
                expected_generation=generation, server=server,
            )
            buffer.extend(games)
            games_played += cfg.games_per_iteration

            # ---- 2. real bounded shuffled epochs ----
            train_out = _epoch_train(cfg, net, optimizer, buffer, device)
            optimizer_steps += train_out["steps"]

            # ---- 3. arena gate: candidate vs incumbent best ----
            if iteration % int(getattr(cfg, "arena_every", 10)) == 0:
                outcome = _arena_gate(cfg, net, best_net)
                if outcome["accepted"]:
                    generation += 1
                    best_net.load_state_dict(net.state_dict())
                    best_net.eval()
                    _save_best_atomic(cfg, best_net)
                else:
                    net.load_state_dict(best_net.state_dict())
                    optimizer = _new_optimizer(cfg, net)
                    optimizer_steps = 0
                _log_arena_event(
                    cfg, run_id=run_id, iteration=iteration,
                    generation=generation, wins=outcome["a"],
                    draws=outcome["draws"], losses=outcome["b"],
                    score=outcome["score"], accepted=outcome["accepted"],
                )

            # ---- 4. durable checkpoint after EVERY completed iteration ----
            _save_latest(cfg, run_id=run_id, iteration=iteration,
                         generation=generation,
                         optimizer_steps=optimizer_steps, net=net,
                         best_net=best_net, optimizer=optimizer,
                         buffer=buffer, reason="iteration")
            completed_iteration = iteration
            if iteration % int(getattr(cfg, "checkpoint_every_iterations", 1)) == 0:
                _snapshot_checkpoint(cfg, iteration)

            _log_metrics(cfg, run_id=run_id, iteration=iteration,
                         generation=generation,
                         policy_loss=train_out["policy_loss"],
                         value_loss=train_out["value_loss"],
                         entropy=train_out["entropy"],
                         optimizer_steps=optimizer_steps,
                         replay_size=len(buffer), games=games_played)
            print(
                f"iter {iteration:4d}  gen {generation}  steps {optimizer_steps}"
                f"  buffer {len(buffer)}",
                flush=True,
            )
            if on_iteration is not None:
                on_iteration(iteration)
    except BaseException:
        interrupted = True
        raise
    finally:
        # Shutdown: signal workers, give them a beat to finish the current
        # game, then hard-stop anything left and stop the server.
        stop_event.set()
        for p in procs:
            p.join(timeout=2.0)
        for p in procs:
            if p.is_alive():
                p.terminate()
        for p in procs:
            p.join(timeout=2.0)
        server.stop()
        # Never persist a partially completed parallel iteration. Completed
        # iterations were checkpointed before metrics/callbacks above.
        if interrupted:
            if completed_iteration >= start_iteration:
                _mark_checkpoint_reason(cfg, "interrupt")
            reason = "interrupt"
        elif completed_iteration >= start_iteration:
            _save_latest(cfg, run_id=run_id, iteration=completed_iteration,
                         generation=generation,
                         optimizer_steps=optimizer_steps, net=net,
                         best_net=best_net, optimizer=optimizer,
                         buffer=buffer, reason="final")
            reason = "final"
        else:
            reason = "interrupt" if interrupted else "final"
        print(
            f"{'Training interrupted' if interrupted else 'Training complete.'} "
            f"(saved iteration {completed_iteration}, reason={reason})",
            flush=True,
        )
    _save_best_atomic(cfg, best_net)
    if not interrupted:
        print("Training complete.", flush=True)


if __name__ == "__main__":
    import argparse

    p = argparse.ArgumentParser(description="AlphaZero-style chess self-play trainer")
    p.add_argument(
        "--resume",
        action="store_true",
        help="Resume from checkpoints/latest.pt if present",
    )
    p.add_argument(
        "--workers",
        type=int,
        default=0,
        help="Parallel self-play worker processes (0 = serial loop; >=2 = process pool)",
    )
    args = p.parse_args()
    if args.workers >= 2:
        run_parallel(resume=args.resume, num_workers=args.workers)
    else:
        run(resume=args.resume)
