"""Training loop for the AlphaZero-style chess learner (v2, Sprint A/C).

run() orchestrates: self-play (teacher = accepted best) -> real bounded shuffled
epochs -> arena gate -> durable checkpoint. CPU-friendly: everything runs on
cfg.device (auto CPU if no CUDA).

Checkpointing (schema_version=2):
  - `latest.pt` : full resumable training state written ATOMICALLY after every
                  completed iteration and again in `finally` on graceful
                  interruption (reason="interrupt") or normal completion
                  (reason="final").  Payload: schema_version, run_id,
                  iteration, generation, optimizer_steps, candidate, best,
                  optimizer, torch/cuda/random/numpy RNGs, compressed replay
                  (state_dict), and a JSON-safe config snapshot.
  - `checkpoint_meta.json` : sidecar written atomically next to latest.pt with
                  the same run_id/iteration/generation/optimizer_steps plus
                  reason and saved_at.
  - `ckpt-iterNNNN-<timestamp>.pt` : hardlink snapshot of each per-iteration
                  latest.pt (never overwritten), so checkpoint history is
                  countable.
  - `best.pt`    : serving artifact holding the accepted best net's state dict.

Resume:  `resume=True` restores candidate, accepted best, optimizer, RNGs,
compressed replay, run_id, generation, iteration and the config snapshot.
Legacy v1 snapshots (no schema_version, or schema_version != 2) raise
IncompatibleCheckpointError with a clear message and are NEVER auto-loaded; a
fresh (non-resume) start archives any stale latest.pt instead of reading it.

Learning semantics (Sprint C):
  - training does `training_epochs` real epochs over a bounded sample drawn
    from the replay buffer, freshly shuffled per epoch; each minibatch is one
    optimizer step.  Policy loss (cross-entropy), value loss (MSE) and policy
    entropy are tracked separately; optimizer_steps counts actual step() calls.
  - self-play is generated by the ACCEPTED best net; a rejected challenger is
    reverted to best and its optimizer is reset, so it can never silently
    become the next teacher.
  - the arena uses the standard score (wins + 0.5*draws) / games; acceptance
    installs the candidate as best and increments generation.
  - metrics are event-only: iteration records carry run_id/generation/
    policy/value/entropy/optimizer_steps/replay_size/games; arena outcomes are
    separate `event: "arena"` records.

Parallel mode (run_parallel) consumes worker result ENVELOPES ({"kind":
"game"|"error", ...}) with a timeout and worker-liveness checks so a dead
worker or a stuck queue becomes a bounded RuntimeError, never an unbounded
Queue.get() hang.  Legacy raw-example lists are still accepted.
"""

import hashlib
import json
import os
import queue
import random
import shutil
import time
import uuid
from datetime import datetime, timezone

import numpy as np
import torch
import torch.nn.functional as F

from config import Config
from model import ChessNet
from selfplay import play_game
from arena import play_match, generate_arena_openings, arena_suite_hash
from parallel import InferenceServer, worker_loop
from replay import ReplayBuffer, PinnedReplayLoader
import native_selfplay
import telemetry

Adam = torch.optim.Adam  # module alias so tests can substitute a spy

# NOTE (schema versioning): the on-disk ``schema_version`` integer stays 2 —
# the existing v2 suite pins ``payload["schema_version"] == CHECKPOINT_SCHEMA_VERSION == 2``.
# The Task 8 "schema-v3" feature layer (architecture_id, AMP GradScaler state,
# actor RNG, replay/config compatibility fields, version-aware validation) is
# carried on top: every new checkpoint additionally marks
# ``checkpoint_format == "schema-v3"`` and is validated BEFORE any
# load_state_dict.  Unknown future schemas raise IncompatibleCheckpointError
# and are never labeled "v1".
CHECKPOINT_SCHEMA_VERSION = 2
CHECKPOINT_FORMAT_V3 = "schema-v3"
METRICS_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "training.jsonl")

# Training-state parameters that must match the checkpoint or resume is
# silently corrupt: body identity, tensor sizes, optimizer shape and the
# sampled-minibatch schedule.  Checked by the version-aware loader.
CRITICAL_CONFIG_KEYS = (
    "architecture_id", "num_res_blocks", "num_filters", "num_input_planes",
    "board_size", "policy_planes", "policy_size", "learning_rate",
    "weight_decay", "train_batch_size", "training_epochs", "replay_buffer_size",
)


class IncompatibleCheckpointError(RuntimeError):
    """Raised when a resume target is not a schema_version=2 checkpoint."""


# --------------------------------------------------------------------------- #
#  logging / metrics                                                           #
# --------------------------------------------------------------------------- #

def _metrics_path(cfg):
    return getattr(cfg, "metrics_path", None) or METRICS_PATH


def _gpu_stats(inference_fn):
    """Canonical GPU-side inference counters from the runtime, or {}.

    The trainer merges ``inference_fn.runtime.stats()`` into the per-iteration
    ``resource`` / ``selfplay`` records (design §3.3).  The native self-play
    numbers and the GPU-runtime numbers should agree; the relationship (not
    exact equality across backends) is what the telemetry tests assert.
    Swallow-guarded: a broken/missing runtime contributes nothing.
    """
    try:
        runtime = getattr(inference_fn, "runtime", None)
        if runtime is not None and hasattr(runtime, "stats"):
            return dict(runtime.stats())
    except Exception:  # noqa: BLE001 - telemetry must never kill training
        pass
    return {}


def _log_metrics(cfg, *, run_id, iteration, generation, policy_loss,
                 value_loss, entropy, optimizer_steps, replay_size, games,
                 round_seed=None):
    """Append one iteration record to the metrics file (machine-readable).

    ``round_seed`` (the derived self-play round seed, native backend only) is
    an OPTIONAL extra field: absent from the python/parallel paths, ignored by
    legacy readers.
    """
    try:
        rec = {
            "t": time.time(),
            "run_id": run_id,
            "iteration": int(iteration),
            "generation": int(generation),
            "policy_loss": round(float(policy_loss), 6),
            "value_loss": round(float(value_loss), 6),
            "entropy": round(float(entropy), 6),
            "optimizer_steps": int(optimizer_steps),
            "replay_size": int(replay_size),
            "games": int(games),
        }
        if round_seed is not None:
            rec["round_seed"] = int(round_seed)
        with open(_metrics_path(cfg), "a") as f:
            f.write(json.dumps(rec) + "\n")
    except Exception:  # noqa: BLE001 - observability must never kill training
        pass


def _log_arena_event(cfg, *, run_id, iteration, generation, wins, draws,
                     losses, score, accepted, opening_seed=None,
                     opening_pairs=None, opening_suite_hash=None):
    """Append one event-only arena record (never folded into iteration metrics).

    ``opening_seed`` / ``opening_pairs`` / ``opening_suite_hash`` describe the
    deterministic paired-opening suite used for this arena event and are
    OPTIONAL extra fields (ignored by legacy readers).
    """
    try:
        rec = {
            "t": time.time(),
            "run_id": run_id,
            "event": "arena",
            "iteration": int(iteration),
            "generation": int(generation),
            "wins": int(wins),
            "draws": int(draws),
            "losses": int(losses),
            "score": round(float(score), 6),
            "accepted": bool(accepted),
        }
        if opening_seed is not None:
            rec["opening_seed"] = int(opening_seed)
        if opening_pairs is not None:
            rec["opening_pairs"] = int(opening_pairs)
        if opening_suite_hash is not None:
            rec["opening_suite_hash"] = str(opening_suite_hash)
        with open(_metrics_path(cfg), "a") as f:
            f.write(json.dumps(rec) + "\n")
    except Exception:  # noqa: BLE001
        pass


# --------------------------------------------------------------------------- #
#  config snapshot / run identity                                              #
# --------------------------------------------------------------------------- #

def _config_snapshot(cfg):
    """JSON-safe subset of the config (class attrs + instance overrides)."""
    snap = {}
    for k in dir(cfg):
        if k.startswith("_"):
            continue
        try:
            v = getattr(cfg, k)
        except Exception:  # noqa: BLE001
            continue
        if isinstance(v, (str, int, float, bool)) or v is None:
            snap[k] = v
    return snap


def _make_run_id(cfg):
    rid = getattr(cfg, "run_id", None)
    if rid:
        return str(rid)
    return uuid.uuid4().hex[:12]


def _seed_all(seed):
    torch.manual_seed(seed)
    random.seed(seed)
    np.random.seed(seed)


# --------------------------------------------------------------------------- #
#  schema-v3 compatibility helpers (Task 8)                                   #
# --------------------------------------------------------------------------- #

def _device_type(device):
    """'cuda' | 'cpu' — backend identity stored in / validated against
    checkpoints (a CUDA-trained run with AMP scaler state must not silently
    resume on CPU)."""
    return "cuda" if str(device).split(":")[0] == "cuda" else "cpu"


def _config_fingerprint(cfg):
    """Stable hash of the CRITICAL_CONFIG_KEYS subset of a config.  Two runs
    with different critical configs get different fingerprints, so a resume
    with silently-changed training semantics is rejected."""
    snap = {}
    for k in CRITICAL_CONFIG_KEYS:
        snap[k] = getattr(cfg, k, None)
    return hashlib.sha256(
        json.dumps(snap, sort_keys=True, default=str).encode("utf-8")
    ).hexdigest()[:16]


def _amp_enabled(cfg, device):
    """Mixed precision is on only for real CUDA devices (CPU training stays
    FP32 and the GradScaler becomes a passthrough)."""
    return bool(
        getattr(cfg, "amp", True)
        and _device_type(device) == "cuda"
        and torch.cuda.is_available()
    )


def _make_grad_scaler(enabled):
    """torch.amp.GradScaler with a fallback for older torch versions."""
    try:
        device_type = "cuda" if torch.cuda.is_available() else "cpu"
        return torch.amp.GradScaler(device_type, enabled=bool(enabled))
    except (AttributeError, TypeError):  # pragma: no cover - torch < 2.3
        return torch.cuda.amp.GradScaler(enabled=bool(enabled))


def _new_scaler(cfg, device):
    """Persistent GradScaler owned by the training loop (checkpointed)."""
    return _make_grad_scaler(_amp_enabled(cfg, device))


# --------------------------------------------------------------------------- #
#  checkpointing (schema_version=2)                                            #
# --------------------------------------------------------------------------- #

def _checkpoint_paths(cfg):
    return {
        "best": os.path.join(cfg.checkpoint_dir, "best.pt"),
        "latest": os.path.join(cfg.checkpoint_dir, "latest.pt"),
        "meta": os.path.join(cfg.checkpoint_dir, "checkpoint_meta.json"),
        "best_meta": os.path.join(cfg.checkpoint_dir, "best_meta.json"),
    }


def _timestamp():
    return time.strftime("%Y%m%d-%H%M%S")


def _save_best_atomic(cfg, net):
    """Atomically publish arena-accepted weights for serving/evaluation.

    Legacy signature kept for callers that have no run metadata; delegates to
    the transactional pair writer ``_publish_best``.
    """
    return _publish_best(cfg, net)


def _publish_best(cfg, net, *, run_id=None, iteration=None, generation=None,
                  architecture_id=None):
    """Transactionally publish ``best.pt`` + ``best_meta.json`` as ONE pair.

    ``best_meta.json`` records the TRUE accepted generation at publish time —
    never inferred from iteration filenames — so a serving/arena consumer can
    tell exactly which generation the weights correspond to, and resume can
    detect (and repair) a best that ran ahead of or behind ``latest.pt``.
    Both files are written via tmp + atomic replace.
    """
    paths = _checkpoint_paths(cfg)
    tmp = paths["best"] + ".tmp"
    torch.save(net.state_dict(), tmp)
    os.replace(tmp, paths["best"])
    meta = {
        "schema_version": CHECKPOINT_SCHEMA_VERSION,
        "checkpoint_format": CHECKPOINT_FORMAT_V3,
        "run_id": run_id,
        "iteration": None if iteration is None else int(iteration),
        "generation": None if generation is None else int(generation),
        "architecture_id": architecture_id
        or getattr(net, "architecture_id", None),
        "policy_size": int(getattr(cfg, "policy_size", 0)),
        "num_input_planes": int(getattr(cfg, "num_input_planes", 0)),
        "board_size": int(getattr(cfg, "board_size", 0)),
        "saved_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    tmp_meta = paths["best_meta"] + ".tmp"
    with open(tmp_meta, "w") as f:
        json.dump(meta, f, indent=2, sort_keys=True)
    os.replace(tmp_meta, paths["best_meta"])
    return paths["best"]


def _save_meta(cfg, *, run_id, iteration, generation, optimizer_steps,
               replay_size, reason, architecture_id=None, provenance=None):
    """Atomically write checkpoint_meta.json next to latest.pt."""
    paths = _checkpoint_paths(cfg)
    meta = {
        "schema_version": CHECKPOINT_SCHEMA_VERSION,
        "checkpoint_format": CHECKPOINT_FORMAT_V3,
        "run_id": run_id,
        "iteration": int(iteration),
        "generation": int(generation),
        "optimizer_steps": int(optimizer_steps),
        "replay_size": int(replay_size),
        "reason": reason,
        "saved_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "architecture_id": architecture_id,
        "config": _config_snapshot(cfg),
    }
    if provenance:
        meta.update(provenance)
    tmp = paths["meta"] + ".tmp"
    with open(tmp, "w") as f:
        json.dump(meta, f, indent=2, sort_keys=True)
    os.replace(tmp, paths["meta"])
    return paths["meta"]


def _mark_checkpoint_reason(cfg, reason):
    """Update only the sidecar reason for an already-durable checkpoint."""
    path = _checkpoint_paths(cfg)["meta"]
    if not os.path.exists(path):
        return None
    with open(path) as f:
        meta = json.load(f)
    meta["reason"] = reason
    meta["saved_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(meta, f, indent=2, sort_keys=True)
    os.replace(tmp, path)
    return path


def _save_latest(cfg, *, run_id, iteration, generation, optimizer_steps,
                 net, best_net, optimizer, buffer, reason, scaler=None,
                 device=None, provenance=None):
    """Persist a full resumable schema-v3 snapshot (atomic) plus
    checkpoint_meta.json (atomic), then transactionally publish the best pair.

    Publication order matters: latest.pt + checkpoint_meta.json go FIRST, and
    best.pt + best_meta.json SECOND, both from the SAME in-memory state — so
    the on-disk best can never run ahead of the resumable latest.pt (and is
    never stale either).  ``best_meta.json`` carries the true accepted
    generation.

    Telemetry (Ticket A): the write runs inside a `PhaseTimer("checkpoint")`
    and a swallow-guarded `phase` record (snapshot=False — the versioned
    hardlink is emitted separately by ``_snapshot_checkpoint``) is appended on
    exit.
    """
    with telemetry.PhaseTimer("checkpoint") as _ckpt_timer:
        paths = _checkpoint_paths(cfg)
        arch_id = getattr(net, "architecture_id", None)
        payload = {
            "schema_version": CHECKPOINT_SCHEMA_VERSION,
            "checkpoint_format": CHECKPOINT_FORMAT_V3,
            "architecture_id": arch_id,
            "policy_size": int(cfg.policy_size),
            "num_input_planes": int(cfg.num_input_planes),
            "board_size": int(cfg.board_size),
            "replay_capacity": int(cfg.replay_buffer_size),
            "backend": _device_type(device if device is not None
                                    else getattr(cfg, "device", "cpu")),
            "config_fingerprint": _config_fingerprint(cfg),
            "scaler": scaler.state_dict() if scaler is not None else {},
            "actor_rng": {
                "numpy": np.random.get_state(),
                "random": random.getstate(),
            },
            "run_id": run_id,
            "iteration": int(iteration),
            "generation": int(generation),
            "optimizer_steps": int(optimizer_steps),
            "candidate": net.state_dict(),
            "best": best_net.state_dict(),
            "optimizer": optimizer.state_dict(),
            "torch_rng": torch.get_rng_state(),
            "cuda_rng": torch.cuda.get_rng_state_all() if torch.cuda.is_available() else None,
            "random_rng": random.getstate(),
            "numpy_rng": np.random.get_state(),
            "replay": buffer.state_dict(),
            "config": _config_snapshot(cfg),
        }
        if provenance:
            payload.update(provenance)
        tmp = paths["latest"] + ".tmp"
        torch.save(payload, tmp)
        os.replace(tmp, paths["latest"])
        _save_meta(cfg, run_id=run_id, iteration=iteration, generation=generation,
                   optimizer_steps=optimizer_steps, replay_size=len(buffer),
                   reason=reason, architecture_id=arch_id, provenance=provenance)
        # Publish best AFTER latest so best.pt never runs ahead of resumable state.
        _publish_best(cfg, best_net, run_id=run_id, iteration=iteration,
                      generation=generation, architecture_id=arch_id)
    try:
        ckpt_bytes = None
        try:
            ckpt_bytes = os.path.getsize(paths["latest"])
        except OSError:
            pass
        telemetry.safe_emit(cfg, {
            "type": "phase",
            "phase": "checkpoint",
            "run_id": run_id,
            "iteration": iteration,
            "generation": generation,
            "duration_s": _ckpt_timer.duration_s,
            "snapshot": False,
            "bytes": ckpt_bytes,
            "reason": reason,
        })
    except Exception:  # noqa: BLE001 - telemetry must never kill training
        pass
    return paths["latest"]


def _validate_checkpoint_compat(cfg, payload):
    """schema-v3 version-aware validation BEFORE any load_state_dict.

    Validates architecture_id (body identity), policy/input/board tensor
    sizes, replay capacity, backend and critical config against the config
    that will build the training state.  Raises IncompatibleCheckpointError
    on ANY mismatch — a v2 body is never silently loaded into a different
    body, and a legacy/unknown schema is never labeled "v1".
    """
    from model import infer_state_dict_architecture_id, resolve_architecture_id
    path = _checkpoint_paths(cfg)["latest"]
    is_v3 = payload.get("checkpoint_format") == CHECKPOINT_FORMAT_V3
    expected_arch = resolve_architecture_id(
        int(getattr(cfg, "num_res_blocks", 6)),
        int(getattr(cfg, "num_filters", 128)),
    )

    # ---- 1. architecture / body identity ----
    payload_arch = payload.get("architecture_id")
    if is_v3:
        if not payload_arch:
            raise IncompatibleCheckpointError(
                f"checkpoint {path} is schema-v3 but carries no "
                "architecture_id; refusing unvalidated load"
            )
        if payload_arch != expected_arch:
            raise IncompatibleCheckpointError(
                f"architecture_id mismatch: checkpoint {path} was trained "
                f"with {payload_arch!r} but this config builds "
                f"{expected_arch!r}. Refusing to load tensors into a "
                "different body (schema-v3 validation)."
            )
    else:
        # legacy v2 (no metadata): infer the body from the raw candidate
        # state dict so a different body is still rejected.
        candidate = payload.get("candidate")
        if not isinstance(candidate, dict):
            raise IncompatibleCheckpointError(
                f"checkpoint {path} has no candidate state_dict; refusing "
                "unvalidated load"
            )
        try:
            inferred = infer_state_dict_architecture_id(candidate)
        except ValueError as e:
            raise IncompatibleCheckpointError(
                f"checkpoint {path} candidate is not a ChessNet body: {e}"
            ) from e
        if inferred != expected_arch:
            raise IncompatibleCheckpointError(
                f"architecture mismatch: legacy checkpoint {path} body is "
                f"{inferred!r} but this config builds {expected_arch!r}. "
                "Refusing to load tensors into a different body."
            )

    # ---- 2. tensor-size compatibility (policy/input/board) ----
    snap = payload.get("config") or {}
    policy_size = payload.get("policy_size", snap.get("policy_size"))
    num_input_planes = payload.get("num_input_planes",
                                   snap.get("num_input_planes"))
    board_size = payload.get("board_size", snap.get("board_size"))
    if policy_size != getattr(cfg, "policy_size", None):
        raise IncompatibleCheckpointError(
            f"policy_size mismatch: checkpoint {path} has {policy_size!r}, "
            f"config has {cfg.policy_size!r}"
        )
    if num_input_planes != getattr(cfg, "num_input_planes", None):
        raise IncompatibleCheckpointError(
            f"num_input_planes mismatch: checkpoint {path} has "
            f"{num_input_planes!r}, config has {cfg.num_input_planes!r}"
        )
    if board_size != getattr(cfg, "board_size", None):
        raise IncompatibleCheckpointError(
            f"board_size mismatch: checkpoint {path} has {board_size!r}, "
            f"config has {cfg.board_size!r}"
        )

    # ---- 3. replay capacity ----
    replay_sd = payload.get("replay")
    if not isinstance(replay_sd, dict) or "capacity" not in replay_sd:
        raise IncompatibleCheckpointError(
            f"checkpoint {path} has no replay state_dict; refusing "
            "unvalidated load"
        )
    if int(replay_sd["capacity"]) != int(getattr(cfg, "replay_buffer_size", 0)):
        raise IncompatibleCheckpointError(
            f"replay capacity mismatch: checkpoint {path} replay holds "
            f"{int(replay_sd['capacity'])} examples, config wants "
            f"{int(getattr(cfg, 'replay_buffer_size', 0))}. A resized replay "
            "would silently change sampling semantics."
        )

    # ---- 4. backend (CUDA-trained run never resumes silently on CPU) ----
    payload_backend = payload.get("backend")
    if payload_backend is None:
        payload_backend = _device_type(snap.get("device", "cpu"))
    cur_backend = _device_type(getattr(cfg, "device", "cpu"))
    if payload_backend == "cuda" and cur_backend != "cuda":
        raise IncompatibleCheckpointError(
            f"backend mismatch: checkpoint {path} was trained on CUDA (with "
            "AMP GradScaler state) but this process runs on CPU; refusing to "
            "silently resume mixed-precision training on a different backend."
        )

    # ---- 5. critical config fingerprint ----
    if is_v3:
        fp = payload.get("config_fingerprint")
        if fp != _config_fingerprint(cfg):
            raise IncompatibleCheckpointError(
                f"config fingerprint mismatch: checkpoint {path} was trained "
                f"with a different critical config (fingerprint {fp!r} vs "
                f"current {_config_fingerprint(cfg)!r}). Refusing resume."
            )
    else:
        for k in CRITICAL_CONFIG_KEYS:
            if k in snap and snap[k] != getattr(cfg, k, None):
                raise IncompatibleCheckpointError(
                    f"critical config mismatch on {k}: checkpoint {path} has "
                    f"{snap[k]!r}, config has {getattr(cfg, k, None)!r}"
                )


def _load_latest_v2(cfg):
    """Return the latest resumable snapshot, or None if it doesn't exist.

    Version-aware (schema-v3): validates architecture_id / tensor sizes /
    replay capacity / backend / critical config BEFORE any load_state_dict.
    Raises IncompatibleCheckpointError for legacy v1 or UNKNOWN schemas —
    an unknown future schema is never labeled "v1" and never auto-loaded.
    """
    path = _checkpoint_paths(cfg)["latest"]
    if not os.path.exists(path):
        return None
    # weights_only=False: the snapshot is self-created and trusted, and it
    # carries non-tensor state (numpy/RNG) that weights_only=True rejects.
    payload = torch.load(path, map_location=getattr(cfg, "device", "cpu"),
                         weights_only=False)
    version = payload.get("schema_version")
    if version is None or version == 1:
        raise IncompatibleCheckpointError(
            f"checkpoint {path} has schema_version={version!r}; expected "
            f"{CHECKPOINT_SCHEMA_VERSION}. This looks like a v1 snapshot — "
            "v1 snapshots are not auto-loadable. Start fresh (or convert) "
            "and resume only from a current latest.pt."
        )
    if version != CHECKPOINT_SCHEMA_VERSION:
        raise IncompatibleCheckpointError(
            f"checkpoint {path} has schema_version={version!r}; supported "
            f"version is {CHECKPOINT_SCHEMA_VERSION} (schema-v2 / "
            "schema-v3 feature layer). This is an UNKNOWN future/foreign "
            "schema, not a v1 snapshot, and will never be auto-loaded."
        )
    _validate_checkpoint_compat(cfg, payload)
    return payload


def _load_warm_start(cfg, path):
    """Load ONLY the accepted-best weights + provenance from a compatible
    schema-v3 checkpoint, for a weights-only warm start (new training lineage).

    Validates schema, checkpoint_format, architecture_id, tensor sizes and the
    state-dict body BEFORE any load_state_dict.  Does NOT return (and the
    caller must not load) replay, optimizer, GradScaler, RNG state, run_id or
    the source iteration counter.  Raises IncompatibleCheckpointError on any
    mismatch.
    """
    from model import infer_state_dict_architecture_id, resolve_architecture_id

    if not os.path.exists(path):
        raise IncompatibleCheckpointError(f"warm-start checkpoint not found: {path}")
    payload = torch.load(path, map_location="cpu", weights_only=False)
    version = payload.get("schema_version")
    if version != CHECKPOINT_SCHEMA_VERSION:
        raise IncompatibleCheckpointError(
            f"warm-start checkpoint {path} has schema_version={version!r}; "
            f"expected {CHECKPOINT_SCHEMA_VERSION}. Refusing warm start."
        )
    if payload.get("checkpoint_format") != CHECKPOINT_FORMAT_V3:
        raise IncompatibleCheckpointError(
            f"warm-start checkpoint {path} is not schema-v3 "
            f"(checkpoint_format={payload.get('checkpoint_format')!r}); "
            "refusing unvalidated warm start."
        )
    expected_arch = resolve_architecture_id(
        int(getattr(cfg, "num_res_blocks", 6)),
        int(getattr(cfg, "num_filters", 128)),
    )
    payload_arch = payload.get("architecture_id")
    if payload_arch != expected_arch:
        raise IncompatibleCheckpointError(
            f"architecture_id mismatch: warm-start checkpoint {path} was "
            f"trained with {payload_arch!r} but this config builds "
            f"{expected_arch!r}. Refusing warm start."
        )
    if payload.get("policy_size") != getattr(cfg, "policy_size", None):
        raise IncompatibleCheckpointError(
            f"policy_size mismatch in warm-start checkpoint {path}"
        )
    if payload.get("num_input_planes") != getattr(cfg, "num_input_planes", None):
        raise IncompatibleCheckpointError(
            f"num_input_planes mismatch in warm-start checkpoint {path}"
        )
    if payload.get("board_size") != getattr(cfg, "board_size", None):
        raise IncompatibleCheckpointError(
            f"board_size mismatch in warm-start checkpoint {path}"
        )
    best_sd = payload.get("best")
    if not isinstance(best_sd, dict):
        raise IncompatibleCheckpointError(
            f"warm-start checkpoint {path} has no accepted-best state_dict"
        )
    inferred = infer_state_dict_architecture_id(best_sd)
    if inferred != expected_arch:
        raise IncompatibleCheckpointError(
            f"warm-start checkpoint {path} best body is {inferred!r} but this "
            f"config builds {expected_arch!r}. Refusing warm start."
        )
    return {
        "best": best_sd,
        "parent_run_id": payload.get("run_id"),
        "parent_iteration": payload.get("iteration"),
        "parent_generation": payload.get("generation"),
        "warm_started_from": os.path.abspath(path),
    }


def _restore_rng(state):
    """Restore torch/cuda/random/numpy RNG states from a snapshot.

    Schema-v3 snapshots carry an explicit ``actor_rng`` (the RNG state
    consumed by self-play policy sampling / MCTS Dirichlet noise); legacy
    snapshots fall back to the top-level ``random_rng``/``numpy_rng``.
    """
    rng = state["torch_rng"]
    torch.set_rng_state(rng.cpu() if rng.is_cuda else rng)
    if state.get("cuda_rng") and torch.cuda.is_available():
        cuda_rng = state["cuda_rng"]
        if isinstance(cuda_rng, (list, tuple)) and all(
            hasattr(r, "cpu") for r in cuda_rng
        ):
            torch.cuda.set_rng_state_all(
                [r.cpu() if r.is_cuda else r for r in cuda_rng]
            )
    actor = state.get("actor_rng")
    if isinstance(actor, dict) and "random" in actor and "numpy" in actor:
        random.setstate(actor["random"])
        np.random.set_state(actor["numpy"])
    else:
        random.setstate(state["random_rng"])
        np.random.set_state(state["numpy_rng"])


def _reconcile_best(cfg, payload, best_net):
    """Ensure the on-disk best pair (best.pt + best_meta.json) agrees with the
    resumable latest.pt.  best.pt must never run ahead of (or behind) the
    resumable best: whenever the sidecar generation/run_id disagrees with the
    checkpoint, re-publish the pair from the checkpoint's accepted best."""
    best_meta_path = _checkpoint_paths(cfg)["best_meta"]
    gen = int(payload["generation"])
    rid = payload.get("run_id")
    if os.path.exists(best_meta_path):
        try:
            with open(best_meta_path) as f:
                meta = json.load(f)
            if meta.get("run_id") == rid and meta.get("generation") == gen:
                return  # consistent pair, nothing to do
        except (OSError, ValueError):
            pass
    _publish_best(cfg, best_net, run_id=rid,
                  iteration=int(payload["iteration"]), generation=gen,
                  architecture_id=payload.get("architecture_id"))


def _archive_best(cfg):
    """Move an existing best.pt out of the way before it's overwritten, so a
    fresh (non-resume) start can never silently destroy the incumbent best net."""
    best_path = _checkpoint_paths(cfg)["best"]
    if os.path.exists(best_path):
        archived = os.path.join(cfg.checkpoint_dir, f"best-{_timestamp()}.pt")
        os.replace(best_path, archived)
        print(f"Archived previous best -> {os.path.basename(archived)}", flush=True)


def _archive_latest(cfg):
    """Move an existing latest.pt out of the way on a fresh (non-resume) start
    so a legacy/foreign snapshot is preserved and never silently loaded."""
    latest_path = _checkpoint_paths(cfg)["latest"]
    if os.path.exists(latest_path):
        archived = os.path.join(cfg.checkpoint_dir, f"latest-{_timestamp()}.pt")
        os.replace(latest_path, archived)
        print(f"Archived previous latest -> {os.path.basename(archived)}", flush=True)


def _snapshot_checkpoint(cfg, iteration, *, run_id=None, generation=None):
    """Hardlink the just-written latest.pt to a versioned, never-overwritten
    filename so checkpoints are countable and recoverable after a reset.

    Telemetry (Ticket A): the hardlink runs inside a `PhaseTimer("checkpoint")`
    and a swallow-guarded `phase` record (snapshot=True) is emitted when a
    versioned snapshot was actually taken.
    """
    with telemetry.PhaseTimer("checkpoint") as _ckpt_timer:
        latest_path = _checkpoint_paths(cfg)["latest"]
        if not os.path.exists(latest_path):
            return None
        versioned = os.path.join(
            cfg.checkpoint_dir, f"ckpt-iter{iteration:04d}-{_timestamp()}.pt"
        )
        try:
            os.link(latest_path, versioned)
        except OSError:
            shutil.copy2(latest_path, versioned)
    try:
        if versioned is not None:
            snap_bytes = None
            try:
                snap_bytes = os.path.getsize(versioned)
            except OSError:
                pass
            telemetry.safe_emit(cfg, {
                "type": "phase",
                "phase": "checkpoint",
                "run_id": run_id,
                "iteration": iteration,
                "generation": generation,
                "duration_s": _ckpt_timer.duration_s,
                "snapshot": True,
                "bytes": snap_bytes,
                "reason": "iteration",
            })
    except Exception:  # noqa: BLE001 - telemetry must never kill training
        pass
    return versioned


def _save_milestone(cfg, net, *, run_id, iteration, generation, outcome):
    """Persist an arena-accepted champion as an immutable, weights-only
    milestone under ``<checkpoint_dir>/milestones/``.

    Each arena promotion is an objective strength improvement (the candidate
    beat the incumbent under the deterministic paired-opening suite), so it is
    worth keeping forever at ~8 MB — unlike the ~99 MB full resumable
    snapshots, which are transient rollback material.  Milestones are never
    overwritten; a JSON sidecar records arena provenance (W/D/L, score,
    threshold) plus architecture identity, so each is self-describing and
    re-loadable via the weights-only warm-start path.
    """
    milestones_dir = os.path.join(cfg.checkpoint_dir, "milestones")
    os.makedirs(milestones_dir, exist_ok=True)
    stem = (f"best-gen{int(generation):04d}-iter{int(iteration):04d}-"
            f"{run_id}")
    path = os.path.join(milestones_dir, stem + ".pt")
    meta_path = os.path.join(milestones_dir, stem + ".json")
    tmp = path + ".tmp"
    torch.save(net.state_dict(), tmp)
    os.replace(tmp, path)

    meta = {
        "schema_version": CHECKPOINT_SCHEMA_VERSION,
        "checkpoint_format": CHECKPOINT_FORMAT_V3,
        "run_id": run_id,
        "iteration": int(iteration),
        "generation": int(generation),
        "architecture_id": getattr(net, "architecture_id", None),
        "policy_size": int(getattr(cfg, "policy_size", 0)),
        "num_input_planes": int(getattr(cfg, "num_input_planes", 0)),
        "board_size": int(getattr(cfg, "board_size", 0)),
        "arena": {
            "wins": int(outcome.get("a", 0)),
            "draws": int(outcome.get("draws", 0)),
            "losses": int(outcome.get("b", 0)),
            "score": float(outcome.get("score", 0.0)),
            "accept_threshold": float(
                getattr(cfg, "arena_accept_threshold", 0.55)),
        },
        "saved_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    tmp_meta = meta_path + ".tmp"
    with open(tmp_meta, "w") as f:
        json.dump(meta, f, indent=2, sort_keys=True)
    os.replace(tmp_meta, meta_path)
    print(f"Saved arena milestone -> {os.path.basename(path)}", flush=True)
    return path


# --------------------------------------------------------------------------- #
#  training / arena semantics                                                  #
# --------------------------------------------------------------------------- #

def _new_optimizer(cfg, net):
    return Adam(net.parameters(), lr=cfg.learning_rate,
                weight_decay=getattr(cfg, "weight_decay", 1e-4))


def _epoch_train(cfg, net, optimizer, buffer, device, scaler=None, *,
                 run_id=None, iteration=None, generation=None,
                 optimizer_steps_total=None):
    """Run `training_epochs` REAL epochs over a bounded, per-epoch-shuffled
    sample from the replay buffer.  Each minibatch is one optimizer step.

    Returns dict(policy_loss, value_loss, entropy, steps, batches) — losses are
    averaged over all minibatches, steps counts actual optimizer.step() calls.

    `scaler` (optional GradScaler) enables mixed-precision training on CUDA:
    the forward/loss run under autocast, the loss is scaled before backward,
    and the optimizer steps through the scaler.  When `scaler` is None or
    disabled (CPU / amp off) the loop is the plain FP32 path.

    Telemetry (Ticket A): the training body runs inside a
    `PhaseTimer("training")` and a swallow-guarded `phase` record is emitted on
    exit (`run_id`/`iteration`/`generation`/`optimizer_steps_total` are the
    loop's running metadata, passed in so the record is complete).
    """
    n = len(buffer)
    epochs = int(getattr(cfg, "training_epochs",
                         getattr(cfg, "epochs_per_iteration", 3)))
    if n == 0 or epochs <= 0:
        return {"policy_loss": 0.0, "value_loss": 0.0, "entropy": 0.0,
                "steps": 0, "batches": 0}
    sample_size = min(
        n,
        int(getattr(cfg, "train_epoch_size", 0)
            or (cfg.train_batch_size * epochs)),
    )
    if sample_size <= 0:
        return {"policy_loss": 0.0, "value_loss": 0.0, "entropy": 0.0,
                "steps": 0, "batches": 0}

    net.train()
    sum_policy = sum_value = sum_entropy = 0.0
    steps = batches = 0
    amp = scaler is not None and bool(getattr(scaler, "_enabled", False))
    with telemetry.PhaseTimer("training") as _train_timer:
        for _ in range(epochs):
            # Uniform sample from the entire replay, freshly shuffled each epoch.
            # Sampling only permutation(sample_size) would repeatedly train the
            # oldest prefix and starve newly generated positions.
            rows = np.random.choice(n, size=sample_size, replace=False)
            for start in range(0, sample_size, cfg.train_batch_size):
                batch_rows = rows[start:start + cfg.train_batch_size]
                states, pis, zs = buffer.sample_indices(batch_rows, device)
                if amp:
                    with torch.autocast(device_type=_device_type(device)):
                        logits, value = net(states)
                        policy_loss = F.cross_entropy(logits, pis)
                        value_loss = F.mse_loss(value, zs)
                        loss = policy_loss + value_loss
                    optimizer.zero_grad(set_to_none=True)
                    scaler.scale(loss).backward()
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    logits, value = net(states)
                    policy_loss = F.cross_entropy(logits, pis)
                    value_loss = F.mse_loss(value, zs)
                    loss = policy_loss + value_loss
                    optimizer.zero_grad(set_to_none=True)
                    loss.backward()
                    optimizer.step()
                probs = F.softmax(logits.float(), dim=1)
                entropy = -(probs * (probs + 1e-12).log()).sum(dim=1).mean()
                sum_policy += float(policy_loss.item())
                sum_value += float(value_loss.item())
                sum_entropy += float(entropy.item())
                steps += 1
                batches += 1
    result = {
        "policy_loss": sum_policy / batches,
        "value_loss": sum_value / batches,
        "entropy": sum_entropy / batches,
        "steps": steps,
        "batches": batches,
    }
    try:
        telemetry.safe_emit(cfg, {
            "type": "phase",
            "phase": "training",
            "run_id": run_id,
            "iteration": iteration,
            "generation": generation,
            "duration_s": _train_timer.duration_s,
            "steps": result["steps"],
            "batches": result["batches"],
            "train_batch_size": int(getattr(cfg, "train_batch_size", 0)),
            "policy_loss": result["policy_loss"],
            "value_loss": result["value_loss"],
            "entropy": result["entropy"],
            "optimizer_steps": int((optimizer_steps_total or 0)
                                   + result["steps"]),
        })
    except Exception:  # noqa: BLE001 - telemetry must never kill training
        pass
    return result


def _arena_gate(cfg, net, best_net, *, run_id=None, iteration=None,
                generation=None):
    """Candidate vs incumbent best.  Standard score = (wins + 0.5*draws)/games.

    The arena uses a deterministic paired-opening suite (generated from
    cfg.arena_seed) so results are comparable across evaluations.  Returns
    dict(a, b, draws, games, score, accepted, opening_seed, opening_pairs,
    opening_suite_hash).

    Telemetry (Ticket A): the ``play_match`` call runs inside a
    `PhaseTimer("arena")` and a swallow-guarded `phase` record with the arena
    fields is emitted on exit.
    """
    net.eval()
    best_net.eval()
    opening_seed = int(getattr(cfg, "arena_seed", 424242))
    num_pairs = int(cfg.arena_games) // 2
    openings = generate_arena_openings(
        num_pairs,
        int(getattr(cfg, "arena_opening_plies", 8)),
        opening_seed,
    )
    suite_hash = arena_suite_hash(openings)
    # play_match regenerates the same deterministic suite internally (seeded by
    # cfg.arena_seed); the hash above describes exactly that suite.
    with telemetry.PhaseTimer("arena") as _arena_timer:
        result = play_match(net, best_net, cfg, num_games=cfg.arena_games)
    wins = int(result["a"])
    losses = int(result["b"])
    draws = int(result["draws"])
    games = wins + losses + draws
    score = (wins + 0.5 * draws) / games if games else 0.0
    accepted = score >= float(getattr(cfg, "arena_accept_threshold", 0.55))
    try:
        telemetry.safe_emit(cfg, {
            "type": "phase",
            "phase": "arena",
            "run_id": run_id,
            "iteration": iteration,
            "generation": generation,
            "duration_s": _arena_timer.duration_s,
            "arena_games": games,
            "arena_sims": int(getattr(cfg, "arena_simulations", 0)),
            "wins": wins,
            "draws": draws,
            "losses": losses,
            "score": score,
            "accepted": accepted,
            "opening_seed": opening_seed,
            "opening_pairs": num_pairs,
            "opening_suite_hash": suite_hash,
        })
    except Exception:  # noqa: BLE001 - telemetry must never kill training
        pass
    return {"a": wins, "b": losses, "draws": draws, "games": games,
            "score": score, "accepted": accepted,
            "opening_seed": opening_seed, "opening_pairs": num_pairs,
            "opening_suite_hash": suite_hash}


# --------------------------------------------------------------------------- #
#  parallel result envelopes (timeout + liveness)                              #
# --------------------------------------------------------------------------- #

def _unpack_worker_result(item):
    """Normalize a parallel self-play result into ("game", examples) or
    ("error", detail).  Accepts the envelope format
    {"kind": "game"|"error", ...} (examples under "examples"/"payload") and
    the legacy raw-example list, so train.py is forward-compatible with
    parallel.py's result envelopes.
    """
    if isinstance(item, dict):
        kind = item.get("kind")
        if kind == "error":
            detail = (item.get("traceback") or item.get("message")
                      or item.get("error") or "unknown worker error")
            return "error", str(detail)
        if kind == "game":
            payload = item.get("examples", item.get("game",
                                                    item.get("payload", None)))
            if payload is None:
                return "unknown", item
            return "game", list(payload)
        return "unknown", item
    if isinstance(item, (list, tuple)):
        return "game", list(item)
    return "unknown", item


def _collect_games(cfg, result_queue, procs, games_needed, stop_event=None,
                   expected_generation=None, server=None):
    """Collect exactly ``games_needed`` game envelopes and flatten examples.

    Queue silence, worker/server death, protocol mismatch, or an error envelope
    becomes a bounded RuntimeError. When ``expected_generation`` is supplied,
    stale games from a previous accepted teacher are discarded.
    """
    timeout = float(getattr(cfg, "result_timeout_seconds", 60))
    examples = []
    game_count = 0
    while game_count < games_needed:
        if stop_event is not None and stop_event.is_set():
            raise RuntimeError("self-play stopped before enough games were collected")
        if server is not None and not server.is_alive():
            detail = server.get_error() if hasattr(server, "get_error") else None
            raise RuntimeError(f"inference server stopped: {detail or 'unknown error'}")
        try:
            item = result_queue.get(timeout=timeout)
        except queue.Empty:
            dead = [p for p in procs if not p.is_alive()]
            if dead:
                raise RuntimeError(
                    f"{len(dead)} self-play worker(s) died while waiting for games"
                )
            if server is not None and not server.is_alive():
                detail = server.get_error() if hasattr(server, "get_error") else None
                raise RuntimeError(f"inference server stopped: {detail or 'unknown error'}")
            raise RuntimeError(
                f"timed out after {timeout}s without a completed self-play game"
            )

        kind, payload = _unpack_worker_result(item)
        if kind == "error":
            raise RuntimeError(f"self-play worker error: {payload}")
        if kind != "game":
            raise RuntimeError(f"unknown self-play result envelope: {item!r}")
        if expected_generation is not None and isinstance(item, dict):
            item_generation = item.get("generation")
            if item_generation is not None and int(item_generation) != int(expected_generation):
                continue
        examples.extend(payload)
        game_count += 1
    return examples


# --------------------------------------------------------------------------- #
#  serial loop                                                                 #
# --------------------------------------------------------------------------- #

def run(cfg=None, resume=False, on_iteration=None, warm_start_checkpoint=None):
    """The full self-play / train / arena loop.

    `on_iteration(iteration)` is called after each completed iteration (and its
    checkpoint); raising from it simulates a graceful interruption, which is
    still checkpointed in `finally`.

    `warm_start_checkpoint` starts a NEW training lineage from the accepted-best
    weights of a compatible schema-v3 checkpoint (empty replay, fresh optimizer,
    new run_id) — mutually exclusive with `resume`.
    """
    if cfg is None:
        cfg = Config()

    _seed_all(cfg.seed)
    os.makedirs(cfg.checkpoint_dir, exist_ok=True)
    device = getattr(cfg, "device", "cpu")

    net = ChessNet(cfg).to(device)
    best_net = ChessNet(cfg).to(device)
    best_net.load_state_dict(net.state_dict())
    optimizer = _new_optimizer(cfg, net)
    scaler = _new_scaler(cfg, device)
    buffer = ReplayBuffer(
        cfg.replay_buffer_size, cfg.policy_size,
        getattr(cfg, "num_input_planes", 104),
        getattr(cfg, "board_size", 8),
    )

    start_iteration = 1
    generation = 0
    optimizer_steps = 0
    run_id = _make_run_id(cfg)
    provenance = None

    if warm_start_checkpoint is not None:
        if resume:
            raise ValueError(
                "--resume and --warm-start-checkpoint are mutually exclusive"
            )
        wm = _load_warm_start(cfg, warm_start_checkpoint)
        net.load_state_dict(wm["best"])
        best_net.load_state_dict(wm["best"])
        # optimizer/scaler/buffer stay fresh (empty) from construction above;
        # generation/steps/iteration reset for the new corrected lineage.
        generation = 0
        optimizer_steps = 0
        start_iteration = 1
        run_id = _make_run_id(cfg)  # new lineage -> new run id
        provenance = {
            "parent_run_id": wm["parent_run_id"],
            "parent_iteration": wm["parent_iteration"],
            "parent_generation": wm["parent_generation"],
            "warm_started_from": wm["warm_started_from"],
        }
        print(
            f"Warm-started new lineage {run_id} from {wm['warm_started_from']} "
            f"(parent run {wm['parent_run_id']}, "
            f"iter {wm['parent_iteration']}, gen {wm['parent_generation']})",
            flush=True,
        )
    elif resume:
        state = _load_latest_v2(cfg)  # raises IncompatibleCheckpointError for v1
        if state is not None:
            net.load_state_dict(state["candidate"])
            best_net.load_state_dict(state["best"])
            optimizer.load_state_dict(state["optimizer"])
            if state.get("scaler"):
                scaler.load_state_dict(state["scaler"])
            _restore_rng(state)
            buffer.load_state_dict(state["replay"])
            run_id = state["run_id"]
            generation = int(state["generation"])
            optimizer_steps = int(state["optimizer_steps"])
            start_iteration = int(state["iteration"]) + 1
            print(
                f"Resumed run {run_id} (next iter {start_iteration}, "
                f"generation {generation}, steps {optimizer_steps})",
                flush=True,
            )

    best_path = _checkpoint_paths(cfg)["best"]
    if not resume:
        _archive_best(cfg)
        _archive_latest(cfg)   # never auto-load a stale/legacy latest.pt
    _save_best_atomic(cfg, best_net)

    games_played = (start_iteration - 1) * cfg.games_per_iteration
    num_iterations = int(getattr(cfg, "num_iterations", 1))
    iteration = start_iteration - 1
    completed_iteration = start_iteration - 1
    interrupted = False
    round_seed = None

    try:
        for iteration in range(start_iteration, num_iterations + 1):
            # ---- 1. self-play with the ACCEPTED best as teacher ----
            net.eval()
            best_net.eval()
            buf_before = len(buffer)
            with telemetry.PhaseTimer("selfplay") as _sp_timer:
                for _ in range(cfg.games_per_iteration):
                    buffer.extend(play_game(best_net, cfg))
                    games_played += 1
            try:
                telemetry.safe_emit(cfg, {
                    "type": "phase",
                    "phase": "selfplay",
                    "run_id": run_id,
                    "iteration": iteration,
                    "generation": generation,
                    "duration_s": _sp_timer.duration_s,
                    "games": cfg.games_per_iteration,
                    "examples": len(buffer) - buf_before,
                })
            except Exception:  # noqa: BLE001 - telemetry must never kill training
                pass

            # ---- 2. real bounded shuffled epochs ----
            train_out = _epoch_train(cfg, net, optimizer, buffer, device, scaler,
                                     run_id=run_id, iteration=iteration,
                                     generation=generation,
                                     optimizer_steps_total=optimizer_steps)
            optimizer_steps += train_out["steps"]

            # ---- 3. arena gate: candidate vs incumbent best ----
            if iteration % int(getattr(cfg, "arena_every", 10)) == 0:
                outcome = _arena_gate(cfg, net, best_net, run_id=run_id,
                                      iteration=iteration, generation=generation)
                if outcome["accepted"]:
                    generation += 1
                    best_net.load_state_dict(net.state_dict())
                    best_net.eval()
                    _save_best_atomic(cfg, best_net)
                    _save_milestone(cfg, best_net, run_id=run_id,
                                    iteration=iteration, generation=generation,
                                    outcome=outcome)
                else:
                    # Rejected challenger: revert to best and reset the
                    # optimizer so it can never silently become the teacher.
                    net.load_state_dict(best_net.state_dict())
                    optimizer = _new_optimizer(cfg, net)
                    optimizer_steps = 0
                _log_arena_event(
                    cfg, run_id=run_id, iteration=iteration,
                    generation=generation, wins=outcome["a"],
                    draws=outcome["draws"], losses=outcome["b"],
                    score=outcome["score"], accepted=outcome["accepted"],
                    opening_seed=outcome.get("opening_seed"),
                    opening_pairs=outcome.get("opening_pairs"),
                    opening_suite_hash=outcome.get("opening_suite_hash"),
                )

            # ---- 4. durable checkpoint after EVERY completed iteration ----
            _save_latest(cfg, run_id=run_id, iteration=iteration,
                         generation=generation,
                         optimizer_steps=optimizer_steps, net=net,
                         best_net=best_net, optimizer=optimizer,
                         buffer=buffer, reason="iteration",
                         scaler=scaler, device=device, provenance=provenance)
            completed_iteration = iteration
            if iteration % int(getattr(cfg, "checkpoint_every_iterations", 1)) == 0:
                _snapshot_checkpoint(cfg, iteration, run_id=run_id,
                                     generation=generation)

            _log_metrics(cfg, run_id=run_id, iteration=iteration,
                         generation=generation,
                         policy_loss=train_out["policy_loss"],
                         value_loss=train_out["value_loss"],
                         entropy=train_out["entropy"],
                         optimizer_steps=optimizer_steps,
                         replay_size=len(buffer), games=games_played,
                         round_seed=round_seed)
            print(
                f"iter {iteration:4d}  gen {generation}  steps {optimizer_steps}"
                f"  buffer {len(buffer)}  "
                f"p {train_out['policy_loss']:.4f} v {train_out['value_loss']:.4f}",
                flush=True,
            )
            if on_iteration is not None:
                on_iteration(iteration)
    except BaseException:
        interrupted = True
        raise
    finally:
        # A partial iteration is never checkpointed. Each completed iteration
        # was already saved atomically above; an interrupt only annotates that
        # last good checkpoint. Normal completion writes a final reason marker.
        if interrupted:
            if completed_iteration >= start_iteration:
                _mark_checkpoint_reason(cfg, "interrupt")
            reason = "interrupt"
        elif completed_iteration >= start_iteration:
            _save_latest(cfg, run_id=run_id, iteration=completed_iteration,
                         generation=generation,
                         optimizer_steps=optimizer_steps, net=net,
                         best_net=best_net, optimizer=optimizer,
                         buffer=buffer, reason="final",
                         scaler=scaler, device=device, provenance=provenance)
            reason = "final"
        else:
            reason = "interrupt" if interrupted else "final"
        print(
            f"{'Training interrupted' if interrupted else 'Training complete.'} "
            f"(saved iteration {completed_iteration}, reason={reason})",
            flush=True,
        )
    _save_best_atomic(cfg, best_net)
    if not interrupted:
        print("Training complete.", flush=True)


# --------------------------------------------------------------------------- #
#  parallel loop                                                               #
# --------------------------------------------------------------------------- #

def run_parallel(cfg=None, resume=False, num_workers=None, on_iteration=None,
                 warm_start_checkpoint=None):
    """Self-play / train / arena loop with parallel self-play worker processes.

    CPU-heavy MCTS work runs in `num_workers` processes (one game each, in
    parallel); a shared GPU inference server (a thread here) coalesces their
    leaf evaluations into fat forward passes.  The trainer process owns the
    training net, the arena incumbent (self-play teacher), and the served
    `search_net` copy.  Worker results are consumed as envelopes with
    timeout + liveness checks (see _collect_games).
    """
    import multiprocessing as mp

    if cfg is None:
        cfg = Config()
    if num_workers is None or num_workers < 1:
        num_workers = max(1, getattr(cfg, "selfplay_workers", 8))

    _seed_all(cfg.seed)
    os.makedirs(cfg.checkpoint_dir, exist_ok=True)
    device = getattr(cfg, "device", "cpu")

    # ---- model / optimizer / resume (same semantics as serial run) ----
    net = ChessNet(cfg).to(device)
    best_net = ChessNet(cfg).to(device)
    best_net.load_state_dict(net.state_dict())
    search_net = ChessNet(cfg).to(device)
    search_net.load_state_dict(net.state_dict())
    search_net.eval()
    optimizer = _new_optimizer(cfg, net)
    scaler = _new_scaler(cfg, device)
    buffer = ReplayBuffer(
        cfg.replay_buffer_size, cfg.policy_size,
        getattr(cfg, "num_input_planes", 104),
        getattr(cfg, "board_size", 8),
    )

    start_iteration = 1
    generation = 0
    optimizer_steps = 0
    run_id = _make_run_id(cfg)
    provenance = None

    if warm_start_checkpoint is not None:
        if resume:
            raise ValueError(
                "--resume and --warm-start-checkpoint are mutually exclusive"
            )
        wm = _load_warm_start(cfg, warm_start_checkpoint)
        net.load_state_dict(wm["best"])
        best_net.load_state_dict(wm["best"])
        generation = 0
        optimizer_steps = 0
        start_iteration = 1
        run_id = _make_run_id(cfg)
        provenance = {
            "parent_run_id": wm["parent_run_id"],
            "parent_iteration": wm["parent_iteration"],
            "parent_generation": wm["parent_generation"],
            "warm_started_from": wm["warm_started_from"],
        }
        print(
            f"Warm-started new lineage {run_id} from {wm['warm_started_from']} "
            f"(parent run {wm['parent_run_id']}, "
            f"iter {wm['parent_iteration']}, gen {wm['parent_generation']})",
            flush=True,
        )
    elif resume:
        state = _load_latest_v2(cfg)  # raises IncompatibleCheckpointError for v1
        if state is not None:
            net.load_state_dict(state["candidate"])
            best_net.load_state_dict(state["best"])
            optimizer.load_state_dict(state["optimizer"])
            if state.get("scaler"):
                scaler.load_state_dict(state["scaler"])
            _restore_rng(state)
            buffer.load_state_dict(state["replay"])
            run_id = state["run_id"]
            generation = int(state["generation"])
            optimizer_steps = int(state["optimizer_steps"])
            start_iteration = int(state["iteration"]) + 1
            # Self-play always starts from the accepted teacher, never the
            # in-progress candidate restored from the checkpoint.
            search_net.load_state_dict(best_net.state_dict())
            print(
                f"Resumed run {run_id} (next iter {start_iteration}, "
                f"generation {generation}, steps {optimizer_steps})",
                flush=True,
            )

    best_path = _checkpoint_paths(cfg)["best"]
    if not resume:
        _archive_best(cfg)
        _archive_latest(cfg)
    _save_best_atomic(cfg, best_net)

    # ---- spawn worker processes + inference server ----
    ctx = mp.get_context("spawn")
    channels = []
    procs = []
    result_queue = ctx.Queue(maxsize=max(8, num_workers * 2))
    stop_event = ctx.Event()
    teacher_generation = ctx.Value("i", generation)
    for i in range(num_workers):
        req_q = ctx.Queue(maxsize=8)
        resp_q = ctx.Queue(maxsize=8)
        channels.append((req_q, resp_q))
        p = ctx.Process(
            target=worker_loop,
            args=(cfg, req_q, resp_q, result_queue, cfg.seed + 1000 + i,
                  stop_event, i, teacher_generation),
            daemon=True,
        )
        procs.append(p)

    server = InferenceServer(
        search_net, device, channels,
        max_batch=getattr(cfg, "inference_max_batch", 4096),
        min_batch=getattr(cfg, "inference_min_batch", 256),
    )
    server.start()
    for p in procs:
        p.start()
    print(
        f"[parallel] {num_workers} self-play workers + inference server",
        flush=True,
    )

    games_played = (start_iteration - 1) * cfg.games_per_iteration
    num_iterations = int(getattr(cfg, "num_iterations", 1))
    iteration = start_iteration - 1
    completed_iteration = start_iteration - 1
    interrupted = False
    round_seed = None

    try:
        for iteration in range(start_iteration, num_iterations + 1):
            # ---- 1. self-play: collect games from workers (teacher = best) ----
            server.update_weights(best_net.state_dict())
            # Publish the generation only after the corresponding weights are
            # live. Games already in progress retain their old tag and are
            # discarded by _collect_games after an arena promotion.
            teacher_generation.value = generation
            with telemetry.PhaseTimer("selfplay") as _sp_timer:
                games = _collect_games(
                    cfg, result_queue, procs, cfg.games_per_iteration, stop_event,
                    expected_generation=generation, server=server,
                )
                buffer.extend(games)
                games_played += cfg.games_per_iteration
            try:
                telemetry.safe_emit(cfg, {
                    "type": "phase",
                    "phase": "selfplay",
                    "run_id": run_id,
                    "iteration": iteration,
                    "generation": generation,
                    "duration_s": _sp_timer.duration_s,
                    "games": cfg.games_per_iteration,
                    "examples": len(games),
                })
            except Exception:  # noqa: BLE001 - telemetry must never kill training
                pass

            # ---- 2. real bounded shuffled epochs ----
            train_out = _epoch_train(cfg, net, optimizer, buffer, device, scaler,
                                     run_id=run_id, iteration=iteration,
                                     generation=generation,
                                     optimizer_steps_total=optimizer_steps)
            optimizer_steps += train_out["steps"]

            # ---- 3. arena gate: candidate vs incumbent best ----
            if iteration % int(getattr(cfg, "arena_every", 10)) == 0:
                outcome = _arena_gate(cfg, net, best_net, run_id=run_id,
                                      iteration=iteration, generation=generation)
                if outcome["accepted"]:
                    generation += 1
                    best_net.load_state_dict(net.state_dict())
                    best_net.eval()
                    _save_best_atomic(cfg, best_net)
                    _save_milestone(cfg, best_net, run_id=run_id,
                                    iteration=iteration, generation=generation,
                                    outcome=outcome)
                else:
                    net.load_state_dict(best_net.state_dict())
                    optimizer = _new_optimizer(cfg, net)
                    optimizer_steps = 0
                _log_arena_event(
                    cfg, run_id=run_id, iteration=iteration,
                    generation=generation, wins=outcome["a"],
                    draws=outcome["draws"], losses=outcome["b"],
                    score=outcome["score"], accepted=outcome["accepted"],
                    opening_seed=outcome.get("opening_seed"),
                    opening_pairs=outcome.get("opening_pairs"),
                    opening_suite_hash=outcome.get("opening_suite_hash"),
                )

            # ---- 4. durable checkpoint after EVERY completed iteration ----
            _save_latest(cfg, run_id=run_id, iteration=iteration,
                         generation=generation,
                         optimizer_steps=optimizer_steps, net=net,
                         best_net=best_net, optimizer=optimizer,
                         buffer=buffer, reason="iteration",
                         scaler=scaler, device=device, provenance=provenance)
            completed_iteration = iteration
            if iteration % int(getattr(cfg, "checkpoint_every_iterations", 1)) == 0:
                _snapshot_checkpoint(cfg, iteration, run_id=run_id,
                                     generation=generation)

            _log_metrics(cfg, run_id=run_id, iteration=iteration,
                         generation=generation,
                         policy_loss=train_out["policy_loss"],
                         value_loss=train_out["value_loss"],
                         entropy=train_out["entropy"],
                         optimizer_steps=optimizer_steps,
                         replay_size=len(buffer), games=games_played,
                         round_seed=round_seed)
            print(
                f"iter {iteration:4d}  gen {generation}  steps {optimizer_steps}"
                f"  buffer {len(buffer)}",
                flush=True,
            )
            if on_iteration is not None:
                on_iteration(iteration)
    except BaseException:
        interrupted = True
        raise
    finally:
        # Shutdown: signal workers, give them a beat to finish the current
        # game, then hard-stop anything left and stop the server.
        stop_event.set()
        for p in procs:
            p.join(timeout=2.0)
        for p in procs:
            if p.is_alive():
                p.terminate()
        for p in procs:
            p.join(timeout=2.0)
        server.stop()
        # Never persist a partially completed parallel iteration. Completed
        # iterations were checkpointed before metrics/callbacks above.
        if interrupted:
            if completed_iteration >= start_iteration:
                _mark_checkpoint_reason(cfg, "interrupt")
            reason = "interrupt"
        elif completed_iteration >= start_iteration:
            _save_latest(cfg, run_id=run_id, iteration=completed_iteration,
                         generation=generation,
                         optimizer_steps=optimizer_steps, net=net,
                         best_net=best_net, optimizer=optimizer,
                         buffer=buffer, reason="final",
                         scaler=scaler, device=device, provenance=provenance)
            reason = "final"
        else:
            reason = "interrupt" if interrupted else "final"
        print(
            f"{'Training interrupted' if interrupted else 'Training complete.'} "
            f"(saved iteration {completed_iteration}, reason={reason})",
            flush=True,
        )
    _save_best_atomic(cfg, best_net)
    if not interrupted:
        print("Training complete.", flush=True)


# --------------------------------------------------------------------------- #
#  native self-play loop                                                       #
# --------------------------------------------------------------------------- #

def run_native(cfg=None, resume=False, on_iteration=None,
               warm_start_checkpoint=None):
    """Self-play / train / arena loop with the native C++ actor + GPU runtime.

    Replaces the Python worker-process self-play (`run_parallel`) with one
    native `Actor` managing `games_per_iteration` concurrent games, feeding the
    GPU through the persistent `InferenceRuntime` (sparse legal-logit gather,
    FP16, pinned buffers).  Training, arena gating, checkpointing and resume
    semantics are identical to the serial `run()`.
    """
    if cfg is None:
        cfg = Config()

    _seed_all(cfg.seed)
    os.makedirs(cfg.checkpoint_dir, exist_ok=True)
    device = getattr(cfg, "device", "cpu")

    net = ChessNet(cfg).to(device)
    best_net = ChessNet(cfg).to(device)
    best_net.load_state_dict(net.state_dict())
    optimizer = _new_optimizer(cfg, net)
    scaler = _new_scaler(cfg, device)
    buffer = ReplayBuffer(
        cfg.replay_buffer_size, cfg.policy_size,
        getattr(cfg, "num_input_planes", 104),
        getattr(cfg, "board_size", 8),
    )

    start_iteration = 1
    generation = 0
    optimizer_steps = 0
    run_id = _make_run_id(cfg)
    provenance = None

    if warm_start_checkpoint is not None:
        if resume:
            raise ValueError(
                "--resume and --warm-start-checkpoint are mutually exclusive"
            )
        wm = _load_warm_start(cfg, warm_start_checkpoint)
        net.load_state_dict(wm["best"])
        best_net.load_state_dict(wm["best"])
        generation = 0
        optimizer_steps = 0
        start_iteration = 1
        run_id = _make_run_id(cfg)
        provenance = {
            "parent_run_id": wm["parent_run_id"],
            "parent_iteration": wm["parent_iteration"],
            "parent_generation": wm["parent_generation"],
            "warm_started_from": wm["warm_started_from"],
        }
        print(
            f"Warm-started new lineage {run_id} from {wm['warm_started_from']} "
            f"(parent run {wm['parent_run_id']}, "
            f"iter {wm['parent_iteration']}, gen {wm['parent_generation']})",
            flush=True,
        )
    elif resume:
        state = _load_latest_v2(cfg)
        if state is not None:
            net.load_state_dict(state["candidate"])
            best_net.load_state_dict(state["best"])
            optimizer.load_state_dict(state["optimizer"])
            if state.get("scaler"):
                scaler.load_state_dict(state["scaler"])
            _restore_rng(state)
            buffer.load_state_dict(state["replay"])
            run_id = state["run_id"]
            generation = int(state["generation"])
            optimizer_steps = int(state["optimizer_steps"])
            start_iteration = int(state["iteration"]) + 1
            print(
                f"Resumed run {run_id} (next iter {start_iteration}, "
                f"generation {generation}, steps {optimizer_steps})",
                flush=True,
            )

    best_path = _checkpoint_paths(cfg)["best"]
    if not resume:
        _archive_best(cfg)
        _archive_latest(cfg)
    _save_best_atomic(cfg, best_net)

    # The GPU inference runtime holds a resident model.  It owns its own copy
    # (never the trainer's best_net, which the arena and checkpointer mutate
    # and read); weights are refreshed from best_net before each self-play
    # round so the actor always plays the accepted incumbent.
    inference_fn = native_selfplay.make_gpu_inference_fn(cfg)
    # Telemetry classification for shared phase records (design §2.1 backend);
    # informational only — never changes training semantics.
    cfg.backend = "native"

    games_played = (start_iteration - 1) * cfg.games_per_iteration
    num_iterations = int(getattr(cfg, "num_iterations", 1))
    iteration = start_iteration - 1
    completed_iteration = start_iteration - 1
    interrupted = False
    round_seed = None

    try:
        for iteration in range(start_iteration, num_iterations + 1):
            # ---- 1. self-play with the ACCEPTED best as teacher ----
            net.eval()
            best_net.eval()
            inference_fn.update_weights(best_net.state_dict())
            # Per-iteration round seed: derived from (cfg.seed, iteration) so
            # consecutive iterations play genuinely new games while resuming at
            # the same iteration boundary reproduces the identical round.
            round_seed = native_selfplay.derive_selfplay_seed(cfg.seed, iteration)
            sp = native_selfplay.NativeSelfPlay(
                cfg,
                inference_fn,
                games=cfg.games_per_iteration,
                weight_version=optimizer_steps,  # monotonically increases
                generation=generation,
                seed=round_seed,
                run_id=run_id,
                iteration=iteration,
            )
            with telemetry.PhaseTimer("selfplay") as _sp_timer:
                sp_examples = sp.run()
            buffer.extend(sp_examples)
            games_played += cfg.games_per_iteration
            try:
                _gstats = _gpu_stats(inference_fn)
                telemetry.safe_emit(cfg, {
                    "type": "phase",
                    "phase": "selfplay",
                    "run_id": run_id,
                    "iteration": iteration,
                    "generation": generation,
                    "duration_s": _sp_timer.duration_s,
                    "games": cfg.games_per_iteration,
                    "examples": len(sp_examples),
                    "inference_calls": sp.inference_calls,
                    **sp.batch_stats,
                    "simulations": sp.simulations,
                    "sims_per_s": (sp.simulations / _sp_timer.duration_s)
                                  if _sp_timer.duration_s > 0 else None,
                    "games_per_hour": (
                        cfg.games_per_iteration * 3600.0 / _sp_timer.duration_s
                    ) if _sp_timer.duration_s > 0 else None,
                    "round_seed": round_seed,
                    **{f"gpu_{k}": v for k, v in _gstats.items()},
                })
            except Exception:  # noqa: BLE001 - telemetry must never kill training
                pass

            # ---- 2. real bounded shuffled epochs ----
            train_out = _epoch_train(cfg, net, optimizer, buffer, device, scaler,
                                     run_id=run_id, iteration=iteration,
                                     generation=generation,
                                     optimizer_steps_total=optimizer_steps)
            optimizer_steps += train_out["steps"]

            # ---- 3. arena gate: candidate vs incumbent best ----
            if iteration % int(getattr(cfg, "arena_every", 10)) == 0:
                outcome = _arena_gate(cfg, net, best_net, run_id=run_id,
                                      iteration=iteration, generation=generation)
                if outcome["accepted"]:
                    generation += 1
                    best_net.load_state_dict(net.state_dict())
                    best_net.eval()
                    _save_best_atomic(cfg, best_net)
                    _save_milestone(cfg, best_net, run_id=run_id,
                                    iteration=iteration, generation=generation,
                                    outcome=outcome)
                else:
                    net.load_state_dict(best_net.state_dict())
                    optimizer = _new_optimizer(cfg, net)
                    optimizer_steps = 0
                _log_arena_event(
                    cfg, run_id=run_id, iteration=iteration,
                    generation=generation, wins=outcome["a"],
                    draws=outcome["draws"], losses=outcome["b"],
                    score=outcome["score"], accepted=outcome["accepted"],
                    opening_seed=outcome.get("opening_seed"),
                    opening_pairs=outcome.get("opening_pairs"),
                    opening_suite_hash=outcome.get("opening_suite_hash"),
                )

            # ---- 4. durable checkpoint after EVERY completed iteration ----
            _save_latest(cfg, run_id=run_id, iteration=iteration,
                         generation=generation,
                         optimizer_steps=optimizer_steps, net=net,
                         best_net=best_net, optimizer=optimizer,
                         buffer=buffer, reason="iteration",
                         scaler=scaler, device=device, provenance=provenance)
            completed_iteration = iteration
            if iteration % int(getattr(cfg, "checkpoint_every_iterations", 1)) == 0:
                _snapshot_checkpoint(cfg, iteration, run_id=run_id,
                                     generation=generation)

            _log_metrics(cfg, run_id=run_id, iteration=iteration,
                         generation=generation,
                         policy_loss=train_out["policy_loss"],
                         value_loss=train_out["value_loss"],
                         entropy=train_out["entropy"],
                         optimizer_steps=optimizer_steps,
                         replay_size=len(buffer), games=games_played,
                         round_seed=round_seed)

            # ---- 5. telemetry: resource + (on cadence) replay diversity ----
            resource_every = max(
                1, int(getattr(cfg, "telemetry_resource_every", 1))
            )
            if iteration % resource_every == 0:
                try:
                    _rec = {"type": "resource",
                            "run_id": run_id,
                            "iteration": iteration,
                            "generation": generation}
                    _rec.update(telemetry.sample_resources())
                    _rec.update({f"gpu_{k}": v
                                 for k, v in _gpu_stats(inference_fn).items()})
                    telemetry.safe_emit(cfg, _rec)
                except Exception:  # noqa: BLE001 - telemetry must never kill training
                    pass
            diversity_every = int(getattr(cfg, "telemetry_diversity_every", None)
                                  or getattr(cfg, "arena_every", 10))
            if diversity_every > 0 and iteration % diversity_every == 0:
                try:
                    _rec = {"type": "diversity",
                            "source": "replay_buffer",
                            "run_id": run_id,
                            "iteration": iteration,
                            "generation": generation}
                    _rec.update(telemetry.replay_diversity(buffer))
                    telemetry.safe_emit(cfg, _rec)
                except Exception:  # noqa: BLE001 - telemetry must never kill training
                    pass
            print(
                f"iter {iteration:4d}  gen {generation}  steps {optimizer_steps}"
                f"  buffer {len(buffer)}  "
                f"p {train_out['policy_loss']:.4f} v {train_out['value_loss']:.4f}",
                flush=True,
            )
            if on_iteration is not None:
                on_iteration(iteration)
    except BaseException:
        interrupted = True
        raise
    finally:
        if interrupted:
            if completed_iteration >= start_iteration:
                _mark_checkpoint_reason(cfg, "interrupt")
            reason = "interrupt"
        elif completed_iteration >= start_iteration:
            _save_latest(cfg, run_id=run_id, iteration=completed_iteration,
                         generation=generation,
                         optimizer_steps=optimizer_steps, net=net,
                         best_net=best_net, optimizer=optimizer,
                         buffer=buffer, reason="final",
                         scaler=scaler, device=device, provenance=provenance)
            reason = "final"
        else:
            reason = "interrupt" if interrupted else "final"
        print(
            f"{'Training interrupted' if interrupted else 'Training complete.'} "
            f"(saved iteration {completed_iteration}, reason={reason})",
            flush=True,
        )
    _save_best_atomic(cfg, best_net)
    if not interrupted:
        print("Training complete.", flush=True)


def build_parser():
    """Argument parser for the trainer (extracted for testability)."""
    import argparse

    p = argparse.ArgumentParser(description="AlphaZero-style chess self-play trainer")
    mode = p.add_mutually_exclusive_group()
    mode.add_argument(
        "--resume",
        action="store_true",
        help="Resume from checkpoints/latest.pt if present",
    )
    mode.add_argument(
        "--warm-start-checkpoint",
        type=str,
        default=None,
        metavar="PATH",
        help="Start a NEW lineage from the accepted-best weights of this "
             "compatible schema-v3 checkpoint (empty replay, fresh optimizer)",
    )
    p.add_argument(
        "--workers",
        type=int,
        default=0,
        help="Parallel self-play worker processes (0 = serial loop; >=2 = process pool)",
    )
    p.add_argument(
        "--selfplay-backend",
        choices=("python", "native"),
        default="python",
        help="Self-play engine: python (worker processes) or native (C++ actor + GPU runtime)",
    )
    p.add_argument("--num-simulations", type=int, default=None)
    p.add_argument("--games-per-iteration", type=int, default=None)
    p.add_argument("--num-iterations", type=int, default=None)
    p.add_argument("--arena-every", type=int, default=None)
    p.add_argument("--checkpoint-dir", type=str, default=None,
                   help="override the checkpoint directory (default: checkpoints/v2)")
    return p


def main(argv=None):
    args = build_parser().parse_args(argv)

    # Apply runnable overrides to a Config before dispatch.
    cfg = None
    if any(v is not None for v in (
            args.num_simulations, args.games_per_iteration,
            args.num_iterations, args.arena_every, args.checkpoint_dir)):
        cfg = Config()
        if args.num_simulations is not None:
            cfg.num_simulations = args.num_simulations
        if args.games_per_iteration is not None:
            cfg.games_per_iteration = args.games_per_iteration
        if args.num_iterations is not None:
            cfg.num_iterations = args.num_iterations
        if args.arena_every is not None:
            cfg.arena_every = args.arena_every
        if args.checkpoint_dir is not None:
            cfg.checkpoint_dir = args.checkpoint_dir

    if args.selfplay_backend == "native":
        run_native(cfg=cfg, resume=args.resume,
                   warm_start_checkpoint=args.warm_start_checkpoint)
    elif args.workers >= 2:
        run_parallel(cfg=cfg, resume=args.resume, num_workers=args.workers,
                     warm_start_checkpoint=args.warm_start_checkpoint)
    else:
        run(cfg=cfg, resume=args.resume,
            warm_start_checkpoint=args.warm_start_checkpoint)


if __name__ == "__main__":
    main()
