#include "position.h"

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>

#include "policy.h"

namespace chess_rl_native {
namespace {

// Extract the raw 4th FEN field (en-passant square) verbatim: "-" or a square
// name. The FEN is assumed already validated by valid_fen().
std::string raw_ep_field(std::string_view fen) {
    std::istringstream input{std::string(fen)};
    std::string placement;
    std::string active_color;
    std::string castling;
    std::string ep;
    input >> placement >> active_color >> castling >> ep;
    return ep;
}

bool all_decimal(std::string_view value) {
    return !value.empty() && std::all_of(value.begin(), value.end(), [](unsigned char c) {
        return std::isdigit(c) != 0;
    });
}

bool valid_fen(std::string_view fen) {
    std::istringstream input{std::string(fen)};
    std::string placement;
    std::string active_color;
    std::string castling;
    std::string ep;
    std::string halfmove;
    std::string fullmove;
    std::string extra;
    if (!(input >> placement >> active_color >> castling >> ep >> halfmove >> fullmove) || (input >> extra)) {
        return false;
    }

    int rank = 0;
    int files = 0;
    int white_kings = 0;
    int black_kings = 0;
    for (char c : placement) {
        if (c == '/') {
            if (files != 8 || ++rank >= 8) return false;
            files = 0;
            continue;
        }
        if (std::isdigit(static_cast<unsigned char>(c))) {
            const int gap = c - '0';
            if (gap < 1 || gap > 8 || files + gap > 8) return false;
            files += gap;
            continue;
        }
        if (std::string_view("PNBRQKpnbrqk").find(c) == std::string_view::npos || files == 8) {
            return false;
        }
        files++;
        if (c == 'K') white_kings++;
        if (c == 'k') black_kings++;
    }
    if (rank != 7 || files != 8 || white_kings != 1 || black_kings != 1) return false;

    if (active_color != "w" && active_color != "b") return false;
    if (castling != "-") {
        if (castling.empty() || castling.find_first_not_of("KQkq") != std::string::npos) return false;
        for (std::size_t i = 0; i < castling.size(); ++i) {
            if (castling.find(castling[i], i + 1) != std::string::npos) return false;
        }
    }
    if (ep != "-") {
        if (ep.size() != 2 || ep[0] < 'a' || ep[0] > 'h' ||
            ((active_color == "w" && ep[1] != '6') || (active_color == "b" && ep[1] != '3'))) {
            return false;
        }
    }
    if (!all_decimal(halfmove) || !all_decimal(fullmove)) return false;
    try {
        const auto half = std::stoull(halfmove);
        const auto full = std::stoull(fullmove);
        if (half > std::numeric_limits<std::uint32_t>::max() || full == 0 ||
            full > std::numeric_limits<std::uint32_t>::max()) {
            return false;
        }
    } catch (const std::exception&) {
        return false;
    }
    return true;
}

std::string square_uci(chess::Square square) {
    return static_cast<std::string>(square);
}

std::string move_uci(const chess::Board& board, const chess::Move& move) {
    const auto from = square_uci(move.from());
    chess::Square to = move.to();
    if (move.typeOf() == chess::Move::CASTLING) {
        const bool king_side = move.to() > move.from();
        to = chess::Square::castling_king_square(king_side, board.sideToMove());
    }
    std::string result = from + square_uci(to);
    if (move.typeOf() == chess::Move::PROMOTION) {
        const auto promotion = move.promotionType();
        if (promotion == chess::PieceType::KNIGHT)
            result += 'n';
        else if (promotion == chess::PieceType::BISHOP)
            result += 'b';
        else if (promotion == chess::PieceType::ROOK)
            result += 'r';
        else if (promotion == chess::PieceType::QUEEN)
            result += 'q';
        else
            throw std::logic_error("invalid promotion type generated by chess library");
    }
    return result;
}

chess::Movelist legal_moves(const chess::Board& board) {
    chess::Movelist moves;
    chess::movegen::legalmoves(moves, board);
    return moves;
}

bool has_legal_en_passant(const chess::Movelist& moves) {
    return std::any_of(moves.begin(), moves.end(), [](const chess::Move& move) {
        return move.typeOf() == chess::Move::ENPASSANT;
    });
}

std::string transposition_key(const chess::Board& board) {
    const auto moves = legal_moves(board);
    std::istringstream input(board.getFen(false));
    std::string placement;
    std::string active_color;
    std::string castling;
    std::string ep;
    if (!(input >> placement >> active_color >> castling >> ep)) {
        throw std::logic_error("chess library returned malformed FEN");
    }
    if (!has_legal_en_passant(moves)) ep = "-";
    return placement + " " + active_color + " " + castling + " " + ep;
}

bool has_insufficient_material(const chess::Board& board, chess::Color color) {
    const auto pawns = board.pieces(chess::PieceType::PAWN);
    const auto knights = board.pieces(chess::PieceType::KNIGHT);
    const auto bishops = board.pieces(chess::PieceType::BISHOP);
    const auto rooks = board.pieces(chess::PieceType::ROOK);
    const auto queens = board.pieces(chess::PieceType::QUEEN);
    const auto kings = board.pieces(chess::PieceType::KING);

    if (static_cast<bool>(board.us(color) & (pawns | rooks | queens))) return false;

    if (static_cast<bool>(board.pieces(chess::PieceType::KNIGHT, color))) {
        return board.us(color).count() <= 2 &&
               !static_cast<bool>(board.us(~color) & ~(kings | queens));
    }

    if (static_cast<bool>(board.pieces(chess::PieceType::BISHOP, color))) {
        auto remaining_bishops = bishops;
        const int square_color = (9 * remaining_bishops.pop()) & 8;
        while (remaining_bishops) {
            if (((9 * remaining_bishops.pop()) & 8) != square_color) return false;
        }
        return !static_cast<bool>(pawns) && !static_cast<bool>(knights);
    }

    return true;
}

bool is_insufficient_material(const chess::Board& board) {
    return has_insufficient_material(board, chess::Color::WHITE) &&
           has_insufficient_material(board, chess::Color::BLACK);
}

constexpr int NUM_PIECE_TYPES = 6;  // PAWN..KING

// Encode the 12 piece planes for one history step (offset = step * 12) from
// `board` into `data` (a flat (planes, 8, 8) float buffer, plane-major with
// each plane laid out rank 0..7 x file 0..7). Bitboard bit `sq` (square index
// rank*8+file, a1=0) maps to plane element `sq`, matching encoding.py
// _bb_to_plane (numpy unpackbits little-endian over the uint64).
void encode_piece_planes(const chess::Board& board, float* data, int step) {
    const int off = step * 12;
    for (int pt = 0; pt < NUM_PIECE_TYPES; ++pt) {
        const chess::PieceType type(static_cast<chess::PieceType::underlying>(pt));
        const std::uint64_t white = board.pieces(type, chess::Color::WHITE).getBits();
        const std::uint64_t black = board.pieces(type, chess::Color::BLACK).getBits();
        float* wp = data + (off + pt) * 64;
        float* bp = data + (off + pt + 6) * 64;
        for (int sq = 0; sq < 64; ++sq) {
            wp[sq] = ((white >> sq) & 1ULL) ? 1.0f : 0.0f;
            bp[sq] = ((black >> sq) & 1ULL) ? 1.0f : 0.0f;
        }
    }
}

std::uint64_t perft_board(chess::Board& board, int depth) {
    if (depth == 0) return 1;
    chess::Movelist moves;
    chess::movegen::legalmoves(moves, board);
    std::uint64_t nodes = 0;
    for (const auto& move : moves) {
        board.makeMove(move);
        nodes += perft_board(board, depth - 1);
        board.unmakeMove(move);
    }
    return nodes;
}

}  // namespace

Position Position::from_fen(std::string_view fen) {
    if (!valid_fen(fen)) throw std::invalid_argument("invalid FEN");
    Position position;
    position.raw_ep_sq_ = raw_ep_field(fen);
    if (!position.board_.setFen(fen)) throw std::invalid_argument("invalid FEN");
    return position;
}

Position Position::from_uci_history(std::string_view start_fen, const std::vector<std::string>& moves) {
    Position position = from_fen(start_fen);
    for (const auto& move : moves) position.push_uci(move);
    return position;
}

std::string Position::fen() const { return board_.getFen(); }

std::vector<std::string> Position::legal_moves_uci() const {
    chess::Movelist moves;
    chess::movegen::legalmoves(moves, board_);
    std::vector<std::string> result;
    result.reserve(static_cast<std::size_t>(moves.size()));
    for (const auto& move : moves) result.push_back(move_uci(board_, move));
    std::sort(result.begin(), result.end());
    return result;
}

std::vector<std::string> Position::history_uci() const {
    return history_uci_;
}

std::vector<std::string> Position::history_fens(int max_steps) const {
    if (max_steps < 1) throw std::invalid_argument("max_steps must be positive");
    std::vector<std::string> result;
    result.reserve(static_cast<std::size_t>(max_steps));
    Position snapshot = *this;
    result.push_back(snapshot.fen());
    while (!snapshot.history_.empty() && static_cast<int>(result.size()) < max_steps) {
        snapshot.pop();
        result.push_back(snapshot.fen());
    }
    return result;
}

bool Position::is_repetition(int count) const {
    if (count < 1) throw std::invalid_argument("repetition count must be positive");
    if (count == 1) return true;

    const auto key = transposition_key(board_);
    int occurrences = 1;
    Position snapshot = *this;
    while (!snapshot.history_.empty()) {
        snapshot.pop();
        if (transposition_key(snapshot.board_) == key && ++occurrences >= count) return true;
    }
    return false;
}

std::optional<Outcome> Position::outcome(bool claim_draw) const {
    const auto moves = legal_moves(board_);
    if (moves.empty()) {
        if (board_.inCheck()) {
            return Outcome{board_.sideToMove() == chess::Color::WHITE ? "black" : "white", "checkmate"};
        }
    }
    if (is_insufficient_material(board_)) return Outcome{"", "insufficient_material"};
    if (moves.empty()) return Outcome{"", "stalemate"};

    if (board_.halfMoveClock() >= 150) return Outcome{"", "seventyfive_moves"};
    if (is_repetition(5)) return Outcome{"", "fivefold_repetition"};

    if (!claim_draw) return std::nullopt;

    if (board_.halfMoveClock() >= 100) return Outcome{"", "fifty_moves"};
    if (board_.halfMoveClock() >= 99) {
        for (const auto& move : moves) {
            chess::Board after = board_;
            after.makeMove<true>(move);
            if (after.halfMoveClock() >= 100 && chess::movegen::anylegalmoves(after)) {
                return Outcome{"", "fifty_moves"};
            }
        }
    }

    if (is_repetition(3)) return Outcome{"", "threefold_repetition"};
    for (const auto& move : moves) {
        Position after = *this;
        // Mirror push_uci's raw en-passant bookkeeping so the copy stays
        // consistent with history_ (pop() reads raw_ep_stack_ in lockstep).
        const bool double_push = after.board_.at<chess::PieceType>(move.from()) == chess::PieceType::PAWN &&
                                 std::abs(move.to().index() - move.from().index()) == 16;
        after.raw_ep_stack_.push_back(after.raw_ep_sq_);
        after.raw_ep_sq_ = double_push ? static_cast<std::string>(move.to().ep_square()) : "-";
        after.history_uci_.push_back(move_uci(after.board_, move));
        after.board_.makeMove<true>(move);
        after.history_.push_back(move);
        if (after.is_repetition(3)) return Outcome{"", "threefold_repetition"};
    }
    return std::nullopt;
}

void Position::push_uci(std::string_view uci) {
    if ((uci.size() != 4 && uci.size() != 5) ||
        std::any_of(uci.begin(), uci.end(), [](unsigned char c) { return std::isspace(c) != 0; })) {
        throw std::invalid_argument("malformed UCI move");
    }
    for (std::size_t i = 0; i < 4; ++i) {
        if ((i % 2 == 0 && (uci[i] < 'a' || uci[i] > 'h')) ||
            (i % 2 == 1 && (uci[i] < '1' || uci[i] > '8'))) {
            throw std::invalid_argument("malformed UCI move");
        }
    }
    if (uci.size() == 5 && std::string_view("qrbn").find(uci[4]) == std::string_view::npos) {
        throw std::invalid_argument("malformed UCI move");
    }

    chess::Movelist moves;
    chess::movegen::legalmoves(moves, board_);
    for (const auto& move : moves) {
        if (move_uci(board_, move) == uci) {
            // python-chess raw en-passant semantics: the skipped square is
            // recorded after ANY pawn double push (white rank 2 -> rank 4,
            // black rank 7 -> rank 5), regardless of whether a legal capture
            // exists; any other move clears it.
            const bool double_push = board_.at<chess::PieceType>(move.from()) == chess::PieceType::PAWN &&
                                     std::abs(move.to().index() - move.from().index()) == 16;
            raw_ep_stack_.push_back(raw_ep_sq_);
            raw_ep_sq_ = double_push ? static_cast<std::string>(move.to().ep_square()) : "-";
            board_.makeMove<true>(move);
            history_.push_back(move);
            history_uci_.emplace_back(uci);
            return;
        }
    }
    throw std::invalid_argument("illegal UCI move");
}

void Position::pop() {
    if (history_.empty()) throw std::out_of_range("position history is empty");
    board_.unmakeMove(history_.back());
    history_.pop_back();
    history_uci_.pop_back();
    raw_ep_sq_ = raw_ep_stack_.back();
    raw_ep_stack_.pop_back();
}

std::string Position::side_to_move() const {
    return board_.sideToMove() == chess::Color::WHITE ? "w" : "b";
}

std::uint32_t Position::halfmove_clock() const noexcept { return board_.halfMoveClock(); }

std::uint32_t Position::fullmove_number() const noexcept { return board_.fullMoveNumber(); }

std::string Position::castling_rights() const {
    const auto rights = board_.getCastleString();
    return rights.empty() ? "-" : rights;
}

std::string Position::ep_square() const {
    const auto square = board_.enpassantSq();
    return square == chess::Square::NO_SQ ? "-" : square_uci(square);
}

std::string Position::raw_ep_square() const { return raw_ep_sq_; }

std::vector<int> Position::legal_move_indices() const {
    chess::Movelist moves;
    chess::movegen::legalmoves(moves, board_);
    std::vector<int> result;
    result.reserve(static_cast<std::size_t>(moves.size()));
    for (const auto& move : moves) {
        result.push_back(move_to_index(move_uci(board_, move)));
    }
    std::sort(result.begin(), result.end());
    return result;
}

std::string Position::index_to_move(int index) const {
    const bool white = board_.sideToMove() == chess::Color::WHITE;
    const int from = index / POLICY_PLANES;
    const bool from_is_pawn = board_.at<chess::PieceType>(chess::Square(from)) == chess::PieceType::PAWN;
    return index_to_move_impl(index, white, from_is_pawn);
}

void Position::encode_planes(float* out, int history_steps) const {
    if (history_steps < 1) throw std::invalid_argument("history_steps must be positive");

    const int num_planes = 12 * history_steps + 8;
    float* data = out;
    std::fill(data, data + num_planes * 64, 0.0f);

    // History piece planes, most recent first (current position = step 0);
    // positions before game start stay all-zero.
    Position snapshot = *this;
    for (int step = 0; step < history_steps; ++step) {
        encode_piece_planes(snapshot.board_, data, step);
        if (snapshot.history_.empty()) break;
        snapshot.pop();
    }

    // Meta planes (offset 12*history_steps) from the CURRENT position.
    const int meta = 12 * history_steps;
    const bool white = board_.sideToMove() == chess::Color::WHITE;
    const std::string castling = castling_rights();
    const float wk = castling.find('K') != std::string::npos ? 1.0f : 0.0f;
    const float wq = castling.find('Q') != std::string::npos ? 1.0f : 0.0f;
    const float bk = castling.find('k') != std::string::npos ? 1.0f : 0.0f;
    const float bq = castling.find('q') != std::string::npos ? 1.0f : 0.0f;
    const float halfmove = static_cast<float>(board_.halfMoveClock() / 100.0);
    const float repetition = is_repetition(2) ? 1.0f : 0.0f;

    for (int sq = 0; sq < 64; ++sq) {
        data[(meta + 0) * 64 + sq] = white ? 1.0f : 0.0f;
        data[(meta + 1) * 64 + sq] = wk;
        data[(meta + 2) * 64 + sq] = wq;
        data[(meta + 3) * 64 + sq] = bk;
        data[(meta + 4) * 64 + sq] = bq;
        data[(meta + 6) * 64 + sq] = halfmove;
        data[(meta + 7) * 64 + sq] = repetition;
    }

    // En-passant target square (single 1.0 at the raw square, verbatim FEN
    // field / last double-push skip square -- NOT legal-EP semantics).
    if (raw_ep_sq_ != "-") {
        const int file = raw_ep_sq_[0] - 'a';
        const int rank = raw_ep_sq_[1] - '1';
        data[(meta + 5) * 64 + rank * 8 + file] = 1.0f;
    }
}

void Position::encode_planes_u8(std::uint8_t* out, int history_steps) const {
    if (history_steps < 1) throw std::invalid_argument("history_steps must be positive");

    // Encode into the float form first, then narrow.  Sharing the one
    // implementation is what guarantees the two encoders can never drift
    // apart: every plane here is a straight 0/1 copy except the halfmove
    // clock, which is re-read from the board rather than recovered from the
    // float (recovering it would round-trip through the /100.0 divide).
    const int num_planes = 12 * history_steps + 8;
    std::vector<float> tmp(static_cast<std::size_t>(num_planes) * 64);
    encode_planes(tmp.data(), history_steps);

    for (std::size_t i = 0; i < tmp.size(); ++i)
        out[i] = tmp[i] != 0.0f ? 1u : 0u;

    const int meta = 12 * history_steps;
    const std::size_t hm = static_cast<std::size_t>(meta + HALFMOVE_META_PLANE) * 64;
    const std::uint32_t clock = board_.halfMoveClock();
    const std::uint8_t stored = static_cast<std::uint8_t>(
        clock > static_cast<std::uint32_t>(HALFMOVE_CLAMP)
            ? HALFMOVE_CLAMP
            : clock);
    for (int sq = 0; sq < 64; ++sq)
        out[hm + static_cast<std::size_t>(sq)] = stored;
}

std::uint64_t perft(std::string_view fen, int depth) {
    if (depth < 0) throw std::invalid_argument("perft depth must be non-negative");
    Position position = Position::from_fen(fen);
    return perft_board(position.board_, depth);
}

}  // namespace chess_rl_native
