#include "position.h"

#include <algorithm>
#include <cctype>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>

namespace chess_rl_native {
namespace {

bool all_decimal(std::string_view value) {
    return !value.empty() && std::all_of(value.begin(), value.end(), [](unsigned char c) {
        return std::isdigit(c) != 0;
    });
}

bool valid_fen(std::string_view fen) {
    std::istringstream input{std::string(fen)};
    std::string placement;
    std::string active_color;
    std::string castling;
    std::string ep;
    std::string halfmove;
    std::string fullmove;
    std::string extra;
    if (!(input >> placement >> active_color >> castling >> ep >> halfmove >> fullmove) || (input >> extra)) {
        return false;
    }

    int rank = 0;
    int files = 0;
    int white_kings = 0;
    int black_kings = 0;
    for (char c : placement) {
        if (c == '/') {
            if (files != 8 || ++rank >= 8) return false;
            files = 0;
            continue;
        }
        if (std::isdigit(static_cast<unsigned char>(c))) {
            const int gap = c - '0';
            if (gap < 1 || gap > 8 || files + gap > 8) return false;
            files += gap;
            continue;
        }
        if (std::string_view("PNBRQKpnbrqk").find(c) == std::string_view::npos || files == 8) {
            return false;
        }
        files++;
        if (c == 'K') white_kings++;
        if (c == 'k') black_kings++;
    }
    if (rank != 7 || files != 8 || white_kings != 1 || black_kings != 1) return false;

    if (active_color != "w" && active_color != "b") return false;
    if (castling != "-") {
        if (castling.empty() || castling.find_first_not_of("KQkq") != std::string::npos) return false;
        for (std::size_t i = 0; i < castling.size(); ++i) {
            if (castling.find(castling[i], i + 1) != std::string::npos) return false;
        }
    }
    if (ep != "-") {
        if (ep.size() != 2 || ep[0] < 'a' || ep[0] > 'h' ||
            ((active_color == "w" && ep[1] != '6') || (active_color == "b" && ep[1] != '3'))) {
            return false;
        }
    }
    if (!all_decimal(halfmove) || !all_decimal(fullmove)) return false;
    try {
        const auto half = std::stoull(halfmove);
        const auto full = std::stoull(fullmove);
        if (half > std::numeric_limits<std::uint32_t>::max() || full == 0 ||
            full > std::numeric_limits<std::uint32_t>::max()) {
            return false;
        }
    } catch (const std::exception&) {
        return false;
    }
    return true;
}

std::string square_uci(chess::Square square) {
    return static_cast<std::string>(square);
}

std::string move_uci(const chess::Board& board, const chess::Move& move) {
    const auto from = square_uci(move.from());
    chess::Square to = move.to();
    if (move.typeOf() == chess::Move::CASTLING) {
        const bool king_side = move.to() > move.from();
        to = chess::Square::castling_king_square(king_side, board.sideToMove());
    }
    std::string result = from + square_uci(to);
    if (move.typeOf() == chess::Move::PROMOTION) {
        const auto promotion = move.promotionType();
        if (promotion == chess::PieceType::KNIGHT)
            result += 'n';
        else if (promotion == chess::PieceType::BISHOP)
            result += 'b';
        else if (promotion == chess::PieceType::ROOK)
            result += 'r';
        else if (promotion == chess::PieceType::QUEEN)
            result += 'q';
        else
            throw std::logic_error("invalid promotion type generated by chess library");
    }
    return result;
}

std::uint64_t perft_board(chess::Board& board, int depth) {
    if (depth == 0) return 1;
    chess::Movelist moves;
    chess::movegen::legalmoves(moves, board);
    std::uint64_t nodes = 0;
    for (const auto& move : moves) {
        board.makeMove(move);
        nodes += perft_board(board, depth - 1);
        board.unmakeMove(move);
    }
    return nodes;
}

}  // namespace

Position Position::from_fen(std::string_view fen) {
    if (!valid_fen(fen)) throw std::invalid_argument("invalid FEN");
    Position position;
    if (!position.board_.setFen(fen)) throw std::invalid_argument("invalid FEN");
    return position;
}

std::string Position::fen() const { return board_.getFen(); }

std::vector<std::string> Position::legal_moves_uci() const {
    chess::Movelist moves;
    chess::movegen::legalmoves(moves, board_);
    std::vector<std::string> result;
    result.reserve(static_cast<std::size_t>(moves.size()));
    for (const auto& move : moves) result.push_back(move_uci(board_, move));
    std::sort(result.begin(), result.end());
    return result;
}

void Position::push_uci(std::string_view uci) {
    if ((uci.size() != 4 && uci.size() != 5) ||
        std::any_of(uci.begin(), uci.end(), [](unsigned char c) { return std::isspace(c) != 0; })) {
        throw std::invalid_argument("malformed UCI move");
    }
    for (std::size_t i = 0; i < 4; ++i) {
        if ((i % 2 == 0 && (uci[i] < 'a' || uci[i] > 'h')) ||
            (i % 2 == 1 && (uci[i] < '1' || uci[i] > '8'))) {
            throw std::invalid_argument("malformed UCI move");
        }
    }
    if (uci.size() == 5 && std::string_view("qrbn").find(uci[4]) == std::string_view::npos) {
        throw std::invalid_argument("malformed UCI move");
    }

    chess::Movelist moves;
    chess::movegen::legalmoves(moves, board_);
    for (const auto& move : moves) {
        if (move_uci(board_, move) == uci) {
            board_.makeMove(move);
            history_.push_back(move);
            return;
        }
    }
    throw std::invalid_argument("illegal UCI move");
}

void Position::pop() {
    if (history_.empty()) throw std::out_of_range("position history is empty");
    board_.unmakeMove(history_.back());
    history_.pop_back();
}

std::string Position::side_to_move() const {
    return board_.sideToMove() == chess::Color::WHITE ? "w" : "b";
}

std::uint32_t Position::halfmove_clock() const noexcept { return board_.halfMoveClock(); }

std::uint32_t Position::fullmove_number() const noexcept { return board_.fullMoveNumber(); }

std::string Position::castling_rights() const {
    const auto rights = board_.getCastleString();
    return rights.empty() ? "-" : rights;
}

std::string Position::ep_square() const {
    const auto square = board_.enpassantSq();
    return square == chess::Square::NO_SQ ? "-" : square_uci(square);
}

std::uint64_t perft(std::string_view fen, int depth) {
    if (depth < 0) throw std::invalid_argument("perft depth must be non-negative");
    Position position = Position::from_fen(fen);
    return perft_board(position.board_, depth);
}

}  // namespace chess_rl_native
